"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from apps.notifications.grpc import notifications_pb2 as _notifications_pb2
from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class NotificationControllerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> NotificationControllerAsyncStub: ...
    List: _grpc.UnaryUnaryMultiCallable[_notifications_pb2.ListRequest, _notifications_pb2.NotificationList]
    Read: _grpc.UnaryUnaryMultiCallable[_notifications_pb2.ReadRequest, _notifications_pb2.ReadResult]
    ReadAll: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _notifications_pb2.ReadAllResult]
    UnreadCount: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _notifications_pb2.UnreadCountResult]

@_typing.type_check_only
class NotificationControllerAsyncStub(NotificationControllerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    List: _aio.UnaryUnaryMultiCallable[_notifications_pb2.ListRequest, _notifications_pb2.NotificationList]  # type: ignore[assignment]
    Read: _aio.UnaryUnaryMultiCallable[_notifications_pb2.ReadRequest, _notifications_pb2.ReadResult]  # type: ignore[assignment]
    ReadAll: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _notifications_pb2.ReadAllResult]  # type: ignore[assignment]
    UnreadCount: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _notifications_pb2.UnreadCountResult]  # type: ignore[assignment]

class NotificationControllerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def List(
        self,
        request: _notifications_pb2.ListRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_notifications_pb2.NotificationList, _abc.Awaitable[_notifications_pb2.NotificationList]]: ...

    @_abc_1.abstractmethod
    def Read(
        self,
        request: _notifications_pb2.ReadRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_notifications_pb2.ReadResult, _abc.Awaitable[_notifications_pb2.ReadResult]]: ...

    @_abc_1.abstractmethod
    def ReadAll(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_notifications_pb2.ReadAllResult, _abc.Awaitable[_notifications_pb2.ReadAllResult]]: ...

    @_abc_1.abstractmethod
    def UnreadCount(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_notifications_pb2.UnreadCountResult, _abc.Awaitable[_notifications_pb2.UnreadCountResult]]: ...

def add_NotificationControllerServicer_to_server(servicer: NotificationControllerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
