# Generated by Django 6.1 on 2026-09-01 13:58

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "slug",
                    models.SlugField(
                        help_text="What the API is asked for, for example main.",
                        max_length=80,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        blank=True, default=dict, help_text='Name per language: {"en-us": "..."}.'
                    ),
                ),
                (
                    "tagline",
                    models.JSONField(
                        blank=True, default=dict, help_text="Short line under the name."
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=dict, help_text="Default meta description."
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Meta keywords per language: {"en-us": ["..."]}.',
                    ),
                ),
                ("logo", models.URLField(blank=True)),
                ("favicon", models.URLField(blank=True)),
                ("og_image", models.URLField(blank=True, verbose_name="Social preview image")),
                (
                    "contact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Free-form contact details: {"email": "..."}.',
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=list, help_text='[{"label": "X", "url": "https://..."}]'
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, help_text="Anything else every client needs."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="What editors call this page.",
                        max_length=80,
                        verbose_name="Page name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The name the API is asked for, for example home or about-us.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order in a generated menu."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="A draft is invisible to the API and readable through a preview link.",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to go live as soon as it is published, or set a date to wait for.",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        blank=True, default=dict, help_text="Meta title per language."
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=dict, help_text="Meta description per language."
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=dict, help_text="Meta keywords per language."
                    ),
                ),
                ("og_image", models.URLField(blank=True, verbose_name="Social preview image")),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"], name="cms_page_status_caf16a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Section name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="The key the client matches on, for example hero.", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to put this section in the library, for use on many pages.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level section. Nesting is one level deep.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to editors, not to readers.",
                        max_length=200,
                        verbose_name="Label",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The key the client reads, for example headline.", max_length=200
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, help_text="Guidance for whoever fills this in.", max_length=300
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text area"),
                            ("html", "HTML"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date and time"),
                            ("email", "Email"),
                            ("link", "Link"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("file", "File"),
                            ("contact", "Contact details"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "multiple",
                    models.BooleanField(
                        default=False, help_text="Store a list of these instead of a single one."
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="The editing screen insists on this in the default language.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Content per language code. Validated against the type above.",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="cms.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SectionPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sorted with the page's own sections, in one list."
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="cms.page",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Only library sections -- ones that belong to no page -- can be placed.",
                        limit_choices_to={"page__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="cms.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared section",
                "verbose_name_plural": "Shared sections",
                "ordering": ("page", "order"),
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Text per language: {"en-us": "About us"}.',
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Any other address: a path, or an external URL.",
                        max_length=500,
                    ),
                ),
                ("new_tab", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level entry. Nesting is one level deep.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.menuitem",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a page in this CMS. Leave empty and fill in a URL instead.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu item",
                "verbose_name_plural": "Menu items",
                "ordering": ("menu", "order"),
                "indexes": [
                    models.Index(fields=["menu", "order"], name="cms_menuite_menu_id_e9b840_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["page", "slug"], name="cms_section_page_id_c1be09_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["page", "order"], name="cms_section_page_id_e82923_idx"),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("page", "slug"), name="unique_page_section_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", True)),
                fields=("slug",),
                name="unique_library_section_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["section", "slug"], name="cms_field_section_39adb4_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["section", "order"], name="cms_field_section_4052ea_idx"),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("section", "slug"), name="unique_section_field_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionplacement",
            constraint=models.UniqueConstraint(
                fields=("page", "section"), name="unique_page_placement"
            ),
        ),
    ]
