# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from infrastructure.oauth.sliding.grpc import oauth_sliding_pb2 as infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure/oauth/sliding/grpc/oauth_sliding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SlidingTokenRpcControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EndSession = channel.unary_unary(
                '/config.oauth_sliding.SlidingTokenRpcController/EndSession',
                request_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/config.oauth_sliding.SlidingTokenRpcController/Refresh',
                request_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RefreshRequest.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Credentials.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/config.oauth_sliding.SlidingTokenRpcController/Revoke',
                request_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RevokeRequest.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.FromString,
                _registered_method=True)
        self.Sessions = channel.unary_unary(
                '/config.oauth_sliding.SlidingTokenRpcController/Sessions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.SessionList.FromString,
                _registered_method=True)


class SlidingTokenRpcControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlidingTokenRpcControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.EndSessionRequest.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RefreshRequest.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Credentials.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RevokeRequest.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.SerializeToString,
            ),
            'Sessions': grpc.unary_unary_rpc_method_handler(
                    servicer.Sessions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.SessionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.oauth_sliding.SlidingTokenRpcController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.oauth_sliding.SlidingTokenRpcController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlidingTokenRpcController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_sliding.SlidingTokenRpcController/EndSession',
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.EndSessionRequest.SerializeToString,
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_sliding.SlidingTokenRpcController/Refresh',
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RefreshRequest.SerializeToString,
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Credentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_sliding.SlidingTokenRpcController/Revoke',
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.RevokeRequest.SerializeToString,
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_sliding.SlidingTokenRpcController/Sessions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_oauth_dot_sliding_dot_grpc_dot_oauth__sliding__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
