# Generated by Django 6.1 on 2026-08-24 12:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oauth_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                ("reuse_detected_at", models.DateTimeField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_families",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_token_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RotatingRefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("admin", "Administrator"),
                            ("expired", "Expired"),
                            ("rotated", "Rotated"),
                            ("reuse", "Reuse detected"),
                            ("password_changed", "Password changed"),
                            ("security_event", "Security event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("rotation_index", models.PositiveIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("reuse_detected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="oauth_rotation.rotatingrefreshtoken",
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="oauth_rotation.rotatingrefreshtoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="oauth_rotation.tokenfamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "rotating refresh token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RotatingAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("admin", "Administrator"),
                            ("expired", "Expired"),
                            ("rotated", "Rotated"),
                            ("reuse", "Reuse detected"),
                            ("password_changed", "Password changed"),
                            ("security_event", "Security event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_tokens",
                        to="oauth_rotation.rotatingrefreshtoken",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="oauth_rotation.tokenfamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "rotating access token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RefreshTokenReuseEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("presented_fingerprint", models.CharField(blank=True, max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refresh_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuse_events",
                        to="oauth_rotation.rotatingrefreshtoken",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reuse_events",
                        to="oauth_rotation.tokenfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenfamily",
            index=models.Index(
                fields=["user", "revoked_at"], name="oauth_rotat_user_id_6c311b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenfamily",
            index=models.Index(fields=["expires_at"], name="oauth_rotat_expires_ad792f_idx"),
        ),
        migrations.AddIndex(
            model_name="rotatingrefreshtoken",
            index=models.Index(
                fields=["user", "expires_at"], name="oauth_rotat_user_id_9883bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rotatingrefreshtoken",
            index=models.Index(
                fields=["family", "rotation_index"], name="oauth_rotat_family__914807_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rotatingrefreshtoken",
            constraint=models.UniqueConstraint(
                fields=("family", "rotation_index"), name="oauth_unique_refresh_rotation"
            ),
        ),
        migrations.AddIndex(
            model_name="rotatingaccesstoken",
            index=models.Index(
                fields=["user", "expires_at"], name="oauth_rotat_user_id_12fdc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rotatingaccesstoken",
            index=models.Index(
                fields=["family", "revoked_at"], name="oauth_rotat_family__49d191_idx"
            ),
        ),
    ]
