"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Award(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    XP_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    MISSION_ID_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    xp: _builtins.int
    reason: _builtins.str
    reference: _builtins.str
    mission_id: _builtins.str
    created_at: _builtins.str
    @_builtins.property
    def metadata(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        xp: _builtins.int = ...,
        reason: _builtins.str = ...,
        reference: _builtins.str = ...,
        mission_id: _builtins.str = ...,
        metadata: _struct_pb2.Struct | None = ...,
        created_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "id", b"id", "metadata", b"metadata", "mission_id", b"mission_id", "reason", b"reason", "reference", b"reference", "xp", b"xp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Award: _TypeAlias = Award  # noqa: Y015

@_typing.final
class AwardList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AWARDS_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    @_builtins.property
    def awards(self) -> _containers.RepeatedCompositeFieldContainer[Global___Award]: ...
    def __init__(
        self,
        *,
        awards: _abc.Iterable[Global___Award] | None = ...,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["awards", b"awards", "count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AwardList: _TypeAlias = AwardList  # noqa: Y015

@_typing.final
class AwardsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AwardsRequest: _TypeAlias = AwardsRequest  # noqa: Y015

@_typing.final
class Club(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    LOGO_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    JOIN_POLICY_FIELD_NUMBER: _builtins.int
    IS_OPEN_FIELD_NUMBER: _builtins.int
    MEMBER_COUNT_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LEVELS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    slug: _builtins.str
    description: _builtins.str
    logo: _builtins.str
    status: _builtins.str
    join_policy: _builtins.str
    is_open: _builtins.bool
    member_count: _builtins.int
    created_at: _builtins.str
    @_builtins.property
    def metadata(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def levels(self) -> _containers.RepeatedCompositeFieldContainer[Global___Level]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        slug: _builtins.str = ...,
        description: _builtins.str = ...,
        logo: _builtins.str = ...,
        status: _builtins.str = ...,
        join_policy: _builtins.str = ...,
        is_open: _builtins.bool = ...,
        member_count: _builtins.int = ...,
        metadata: _struct_pb2.Struct | None = ...,
        created_at: _builtins.str = ...,
        levels: _abc.Iterable[Global___Level] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "description", b"description", "id", b"id", "is_open", b"is_open", "join_policy", b"join_policy", "levels", b"levels", "logo", b"logo", "member_count", b"member_count", "metadata", b"metadata", "name", b"name", "slug", b"slug", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Club: _TypeAlias = Club  # noqa: Y015

@_typing.final
class ClubBrief(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    LOGO_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    slug: _builtins.str
    logo: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        slug: _builtins.str = ...,
        logo: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "logo", b"logo", "name", b"name", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClubBrief: _TypeAlias = ClubBrief  # noqa: Y015

@_typing.final
class ClubList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLUBS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def clubs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Club]: ...
    def __init__(
        self,
        *,
        clubs: _abc.Iterable[Global___Club] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clubs", b"clubs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClubList: _TypeAlias = ClubList  # noqa: Y015

@_typing.final
class ClubRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SLUG_FIELD_NUMBER: _builtins.int
    slug: _builtins.str
    def __init__(
        self,
        *,
        slug: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClubRequest: _TypeAlias = ClubRequest  # noqa: Y015

@_typing.final
class ClubResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLUB_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def club(self) -> Global___Club: ...
    def __init__(
        self,
        *,
        club: Global___Club | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["club", b"club"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["club", b"club"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClubResult: _TypeAlias = ClubResult  # noqa: Y015

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VALUE_LABEL_FIELD_NUMBER: _builtins.int
    FIELDS_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    label: _builtins.str
    description: _builtins.str
    value_label: _builtins.str
    source: _builtins.str
    @_builtins.property
    def fields(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        label: _builtins.str = ...,
        description: _builtins.str = ...,
        value_label: _builtins.str = ...,
        fields: _struct_pb2.Struct | None = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "fields", b"fields", "key", b"key", "label", b"label", "source", b"source", "value_label", b"value_label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class EventList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        events: _abc.Iterable[Global___Event] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EventList: _TypeAlias = EventList  # noqa: Y015

@_typing.final
class JoinRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SLUG_FIELD_NUMBER: _builtins.int
    slug: _builtins.str
    def __init__(
        self,
        *,
        slug: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JoinRequest: _TypeAlias = JoinRequest  # noqa: Y015

@_typing.final
class JoinResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEMBERSHIP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def membership(self) -> Global___Membership: ...
    def __init__(
        self,
        *,
        membership: Global___Membership | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JoinResult: _TypeAlias = JoinResult  # noqa: Y015

@_typing.final
class Leaderboard(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RANKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ranks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Rank]: ...
    def __init__(
        self,
        *,
        ranks: _abc.Iterable[Global___Rank] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ranks", b"ranks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Leaderboard: _TypeAlias = Leaderboard  # noqa: Y015

@_typing.final
class LeaderboardRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LeaderboardRequest: _TypeAlias = LeaderboardRequest  # noqa: Y015

@_typing.final
class LeaveResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEMBERSHIP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def membership(self) -> Global___Membership: ...
    def __init__(
        self,
        *,
        membership: Global___Membership | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LeaveResult: _TypeAlias = LeaveResult  # noqa: Y015

@_typing.final
class Level(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    XP_REQUIRED_FIELD_NUMBER: _builtins.int
    LOGO_FIELD_NUMBER: _builtins.int
    PERKS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    position: _builtins.int
    name: _builtins.str
    xp_required: _builtins.int
    logo: _builtins.str
    perks: _builtins.str
    @_builtins.property
    def metadata(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        position: _builtins.int = ...,
        name: _builtins.str = ...,
        xp_required: _builtins.int = ...,
        logo: _builtins.str = ...,
        perks: _builtins.str = ...,
        metadata: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "logo", b"logo", "metadata", b"metadata", "name", b"name", "perks", b"perks", "position", b"position", "xp_required", b"xp_required"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Level: _TypeAlias = Level  # noqa: Y015

@_typing.final
class LevelList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LEVELS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def levels(self) -> _containers.RepeatedCompositeFieldContainer[Global___Level]: ...
    def __init__(
        self,
        *,
        levels: _abc.Iterable[Global___Level] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["levels", b"levels"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LevelList: _TypeAlias = LevelList  # noqa: Y015

@_typing.final
class LevelsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SLUG_FIELD_NUMBER: _builtins.int
    slug: _builtins.str
    def __init__(
        self,
        *,
        slug: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LevelsRequest: _TypeAlias = LevelsRequest  # noqa: Y015

@_typing.final
class ListClubsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListClubsRequest: _TypeAlias = ListClubsRequest  # noqa: Y015

@_typing.final
class Membership(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    CLUB_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    XP_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    NEXT_LEVEL_FIELD_NUMBER: _builtins.int
    XP_TO_NEXT_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    JOINED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    status: _builtins.str
    xp: _builtins.int
    xp_to_next: _builtins.int
    progress: _builtins.float
    joined_at: _builtins.str
    @_builtins.property
    def club(self) -> Global___ClubBrief: ...
    @_builtins.property
    def level(self) -> Global___Level: ...
    @_builtins.property
    def next_level(self) -> Global___Level: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        club: Global___ClubBrief | None = ...,
        status: _builtins.str = ...,
        xp: _builtins.int = ...,
        level: Global___Level | None = ...,
        next_level: Global___Level | None = ...,
        xp_to_next: _builtins.int = ...,
        progress: _builtins.float = ...,
        joined_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "_next_level", b"_next_level", "club", b"club", "level", b"level", "next_level", b"next_level"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "_next_level", b"_next_level", "club", b"club", "id", b"id", "joined_at", b"joined_at", "level", b"level", "next_level", b"next_level", "progress", b"progress", "status", b"status", "xp", b"xp", "xp_to_next", b"xp_to_next"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__level: _TypeAlias = _typing.Literal["level"]  # noqa: Y015
    _WhichOneofArgType__level: _TypeAlias = _typing.Literal["_level", b"_level"]  # noqa: Y015
    _WhichOneofReturnType__next_level: _TypeAlias = _typing.Literal["next_level"]  # noqa: Y015
    _WhichOneofArgType__next_level: _TypeAlias = _typing.Literal["_next_level", b"_next_level"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__level) -> _WhichOneofReturnType__level | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__next_level) -> _WhichOneofReturnType__next_level | None: ...

Global___Membership: _TypeAlias = Membership  # noqa: Y015

@_typing.final
class MembershipResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEMBERSHIP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def membership(self) -> Global___Membership: ...
    def __init__(
        self,
        *,
        membership: Global___Membership | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["membership", b"membership"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MembershipResult: _TypeAlias = MembershipResult  # noqa: Y015

@_typing.final
class Mission(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    CRITERIA_FIELD_NUMBER: _builtins.int
    XP_FIELD_NUMBER: _builtins.int
    REPEAT_FIELD_NUMBER: _builtins.int
    TARGET_COUNT_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    COMPLETIONS_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    LAST_COMPLETED_AT_FIELD_NUMBER: _builtins.int
    STARTS_AT_FIELD_NUMBER: _builtins.int
    ENDS_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    code: _builtins.str
    title: _builtins.str
    description: _builtins.str
    event: _builtins.str
    xp: _builtins.int
    repeat: _builtins.str
    target_count: _builtins.int
    count: _builtins.int
    completions: _builtins.int
    completed: _builtins.bool
    available: _builtins.bool
    last_completed_at: _builtins.str
    starts_at: _builtins.str
    ends_at: _builtins.str
    @_builtins.property
    def criteria(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        code: _builtins.str = ...,
        title: _builtins.str = ...,
        description: _builtins.str = ...,
        event: _builtins.str = ...,
        criteria: _struct_pb2.Struct | None = ...,
        xp: _builtins.int = ...,
        repeat: _builtins.str = ...,
        target_count: _builtins.int = ...,
        count: _builtins.int = ...,
        completions: _builtins.int = ...,
        completed: _builtins.bool = ...,
        available: _builtins.bool = ...,
        last_completed_at: _builtins.str = ...,
        starts_at: _builtins.str = ...,
        ends_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["criteria", b"criteria"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available", b"available", "code", b"code", "completed", b"completed", "completions", b"completions", "count", b"count", "criteria", b"criteria", "description", b"description", "ends_at", b"ends_at", "event", b"event", "id", b"id", "last_completed_at", b"last_completed_at", "repeat", b"repeat", "starts_at", b"starts_at", "target_count", b"target_count", "title", b"title", "xp", b"xp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Mission: _TypeAlias = Mission  # noqa: Y015

@_typing.final
class MissionList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MISSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def missions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Mission]: ...
    def __init__(
        self,
        *,
        missions: _abc.Iterable[Global___Mission] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["missions", b"missions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MissionList: _TypeAlias = MissionList  # noqa: Y015

@_typing.final
class Rank(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POSITION_FIELD_NUMBER: _builtins.int
    MEMBERSHIP_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    XP_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    IS_YOU_FIELD_NUMBER: _builtins.int
    position: _builtins.int
    membership_id: _builtins.str
    username: _builtins.str
    xp: _builtins.int
    is_you: _builtins.bool
    @_builtins.property
    def level(self) -> Global___Level: ...
    def __init__(
        self,
        *,
        position: _builtins.int = ...,
        membership_id: _builtins.str = ...,
        username: _builtins.str = ...,
        xp: _builtins.int = ...,
        level: Global___Level | None = ...,
        is_you: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "level", b"level"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "is_you", b"is_you", "level", b"level", "membership_id", b"membership_id", "position", b"position", "username", b"username", "xp", b"xp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__level: _TypeAlias = _typing.Literal["level"]  # noqa: Y015
    _WhichOneofArgType__level: _TypeAlias = _typing.Literal["_level", b"_level"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__level) -> _WhichOneofReturnType__level | None: ...

Global___Rank: _TypeAlias = Rank  # noqa: Y015
