# Generated by Django 6.1 on 2026-09-08 10:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="What a ticket in this category starts at unless the client says otherwise.",
                        max_length=16,
                    ),
                ),
                (
                    "first_response_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How long the desk has to say something. Zero means no promise.",
                    ),
                ),
                (
                    "resolution_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How long the desk has to settle it. Zero means no promise.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unset to stop offering it, without touching the tickets already filed.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Where it sits in a picker."),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        help_text="Any CSS colour. Advisory; used by the admin.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CannedReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="How often it has been fetched. Tells the desk what to keep.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Offer it only on tickets in this category. Empty offers it everywhere.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canned_replies",
                        to="support.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "canned replies",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="The short code a person quotes. Generated; never reused.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("chat", "Live chat"), ("ticket", "Support ticket")],
                        default="ticket",
                        max_length=16,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Empty is allowed: a live chat often has no subject until it turns out to need one.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Waiting on the client"),
                            ("on_hold", "On hold"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Whatever the client that opened this wants carried with it. Sent verbatim.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Denormalised so a queue can be ordered by an index rather than an aggregate.",
                        null=True,
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When a member of staff first said something. The SLA clock stops here.",
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("closed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "first_response_due_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Copied from the category when the ticket was opened. Empty means no promise.",
                        null=True,
                    ),
                ),
                ("resolution_due_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="One to five, from the client, once it is settled.",
                        null=True,
                    ),
                ),
                ("rating_comment", models.TextField(blank=True)),
                ("rated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agent who owns it. Empty means it is still in the unassigned queue.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kept as a null on delete: retiring a category must not delete its history.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.category",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Whose problem this is. The one account that always sees the thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="tickets", to="support.tag"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("agent", "Agent"),
                            ("observer", "Observer"),
                        ],
                        default="client",
                        max_length=16,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Everything in this thread older than this has been read. Empty means none of it.",
                        null=True,
                    ),
                ),
                (
                    "notify",
                    models.BooleanField(
                        default=True,
                        help_text="Unset to stay in the thread without being told about every message.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="support.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("reply", "Reply"), ("note", "Internal note"), ("event", "Event")],
                        default="reply",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Everybody in the thread"), ("internal", "Staff only")],
                        default="public",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="For an event, what changed. For a reply, whatever the client attached.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty for something the system said, or for a deleted account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The file's own name, as sent.", max_length=255),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Where the configured storage serves it.", max_length=1000
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=1000)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.message",
                    ),
                ),
                (
                    "upload",
                    models.OneToOneField(
                        blank=True,
                        help_text="What was claimed to create this. Kept so an upload cannot be claimed twice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachment",
                        to="support.upload",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["client", "-created_at"], name="support_tic_client__a88cb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "-last_message_at"], name="support_tic_status_1ebba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assignee", "status"], name="support_tic_assigne_d266e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["kind", "status"], name="support_tic_kind_71b42a_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["closed_at"], name="support_tic_closed__5acd69_idx"),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="support_rating_between_one_and_five",
                violation_error_message="A rating is one to five stars.",
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["user", "-joined_at"], name="support_par_user_id_cabd8e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("ticket", "user"), name="support_one_participation_per_account"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["ticket", "created_at"], name="support_mes_ticket__b9f841_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["author", "-created_at"], name="support_mes_author__80585a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "note"), _negated=True),
                    ("visibility", "internal"),
                    _connector="OR",
                ),
                name="support_note_is_internal",
                violation_error_message="An internal note cannot be public.",
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["owner", "-created_at"], name="support_upl_owner_i_fc58df_idx"
            ),
        ),
    ]
