# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infrastructure.auth.password.grpc import auth_password_pb2 as infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure/auth/password/grpc/auth_password_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PasswordControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Change = channel.unary_unary(
                '/config.auth_password.PasswordController/Change',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ChangeRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
                _registered_method=True)
        self.Forgot = channel.unary_unary(
                '/config.auth_password.PasswordController/Forgot',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ForgotRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetTicket.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/config.auth_password.PasswordController/Login',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/config.auth_password.PasswordController/Logout',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LogoutRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/config.auth_password.PasswordController/Reset',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
                _registered_method=True)
        self.Signup = channel.unary_unary(
                '/config.auth_password.PasswordController/Signup',
                request_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.SignupRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.FromString,
                _registered_method=True)


class PasswordControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forgot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasswordControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ChangeRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.SerializeToString,
            ),
            'Forgot': grpc.unary_unary_rpc_method_handler(
                    servicer.Forgot,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ForgotRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetTicket.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LogoutRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.SerializeToString,
            ),
            'Signup': grpc.unary_unary_rpc_method_handler(
                    servicer.Signup,
                    request_deserializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.SignupRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.auth_password.PasswordController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.auth_password.PasswordController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PasswordController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Change',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ChangeRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forgot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Forgot',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ForgotRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetTicket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Login',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Logout',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LogoutRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Reset',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.ResetRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_password.PasswordController/Signup',
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.SignupRequest.SerializeToString,
            infrastructure_dot_auth_dot_password_dot_grpc_dot_auth__password__pb2.LoginResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
