"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from infrastructure.auth.email_code.grpc import auth_email_code_pb2 as _auth_email_code_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EmailCodeControllerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EmailCodeControllerAsyncStub: ...
    LoginStart: _grpc.UnaryUnaryMultiCallable[_auth_email_code_pb2.LoginStartRequest, _auth_email_code_pb2.Challenge]
    LoginVerify: _grpc.UnaryUnaryMultiCallable[_auth_email_code_pb2.LoginVerifyRequest, _auth_email_code_pb2.LoginResult]
    Logout: _grpc.UnaryUnaryMultiCallable[_auth_email_code_pb2.LogoutRequest, _auth_email_code_pb2.Message]
    SignupStart: _grpc.UnaryUnaryMultiCallable[_auth_email_code_pb2.SignupStartRequest, _auth_email_code_pb2.Challenge]
    SignupVerify: _grpc.UnaryUnaryMultiCallable[_auth_email_code_pb2.SignupVerifyRequest, _auth_email_code_pb2.LoginResult]

@_typing.type_check_only
class EmailCodeControllerAsyncStub(EmailCodeControllerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    LoginStart: _aio.UnaryUnaryMultiCallable[_auth_email_code_pb2.LoginStartRequest, _auth_email_code_pb2.Challenge]  # type: ignore[assignment]
    LoginVerify: _aio.UnaryUnaryMultiCallable[_auth_email_code_pb2.LoginVerifyRequest, _auth_email_code_pb2.LoginResult]  # type: ignore[assignment]
    Logout: _aio.UnaryUnaryMultiCallable[_auth_email_code_pb2.LogoutRequest, _auth_email_code_pb2.Message]  # type: ignore[assignment]
    SignupStart: _aio.UnaryUnaryMultiCallable[_auth_email_code_pb2.SignupStartRequest, _auth_email_code_pb2.Challenge]  # type: ignore[assignment]
    SignupVerify: _aio.UnaryUnaryMultiCallable[_auth_email_code_pb2.SignupVerifyRequest, _auth_email_code_pb2.LoginResult]  # type: ignore[assignment]

class EmailCodeControllerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def LoginStart(
        self,
        request: _auth_email_code_pb2.LoginStartRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_email_code_pb2.Challenge, _abc.Awaitable[_auth_email_code_pb2.Challenge]]: ...

    @_abc_1.abstractmethod
    def LoginVerify(
        self,
        request: _auth_email_code_pb2.LoginVerifyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_email_code_pb2.LoginResult, _abc.Awaitable[_auth_email_code_pb2.LoginResult]]: ...

    @_abc_1.abstractmethod
    def Logout(
        self,
        request: _auth_email_code_pb2.LogoutRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_email_code_pb2.Message, _abc.Awaitable[_auth_email_code_pb2.Message]]: ...

    @_abc_1.abstractmethod
    def SignupStart(
        self,
        request: _auth_email_code_pb2.SignupStartRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_email_code_pb2.Challenge, _abc.Awaitable[_auth_email_code_pb2.Challenge]]: ...

    @_abc_1.abstractmethod
    def SignupVerify(
        self,
        request: _auth_email_code_pb2.SignupVerifyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_email_code_pb2.LoginResult, _abc.Awaitable[_auth_email_code_pb2.LoginResult]]: ...

def add_EmailCodeControllerServicer_to_server(servicer: EmailCodeControllerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
