"""Meta keywords out, Open Graph in, and choices for a Choice field.

Nothing has ranked on the meta keywords tag for over a decade, so the column is
removed rather than deprecated: a box editors dutifully fill in that nothing
reads costs them time every time a page is written. What replaces it is the four
values that *are* read -- the title, description, image and canonical URL a link
to the page becomes when somebody shares it -- on the page and on the site
alike, so a page can override what the site says about it.

`Field.options` arrives with the Choice type, which is the one type whose valid
values are a property of the field rather than of the type.
"""

# Generated by Django 6.1 on 2026-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="keywords",
        ),
        migrations.AddField(
            model_name="field",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Only for a Choice field: ["small", "large"], or [{"value": "sm", "label": "Small"}] to store one word and show another.',
                verbose_name="Choices",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_description",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Falls back to the meta description.",
                verbose_name="Social description",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_title",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Falls back to the meta title.",
                verbose_name="Social title",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_url",
            field=models.URLField(
                blank=True,
                help_text="Where this page really lives, if not here.",
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_description",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Falls back to the meta description.",
                verbose_name="Social description",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_title",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Falls back to the site name.",
                verbose_name="Social title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_url",
            field=models.URLField(
                blank=True,
                help_text="The site's own address, for any page that does not set one.",
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Text area"),
                    ("html", "HTML"),
                    ("markdown", "Markdown"),
                    ("select", "Choice"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("datetime", "Date and time"),
                    ("email", "Email"),
                    ("phone", "Phone number"),
                    ("url", "URL"),
                    ("color", "Colour"),
                    ("link", "Link"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                    ("page", "Page reference"),
                    ("contact", "Contact details"),
                    ("json", "Raw JSON"),
                ],
                default="text",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
