"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Credentials(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_TYPE_FIELD_NUMBER: _builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: _builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: _builtins.int
    EXPIRES_IN_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    token_type: _builtins.str
    access_token: _builtins.str
    refresh_token: _builtins.str
    expires_in: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        token_type: _builtins.str = ...,
        access_token: _builtins.str = ...,
        refresh_token: _builtins.str = ...,
        expires_in: _builtins.int = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_token", b"access_token", "expires_in", b"expires_in", "refresh_token", b"refresh_token", "session_id", b"session_id", "token_type", b"token_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Credentials: _TypeAlias = Credentials  # noqa: Y015

@_typing.final
class EndSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionRequest: _TypeAlias = EndSessionRequest  # noqa: Y015

@_typing.final
class Message(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DETAIL_FIELD_NUMBER: _builtins.int
    detail: _builtins.str
    def __init__(
        self,
        *,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Message: _TypeAlias = Message  # noqa: Y015

@_typing.final
class RefreshRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REFRESH_TOKEN_FIELD_NUMBER: _builtins.int
    refresh_token: _builtins.str
    def __init__(
        self,
        *,
        refresh_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["refresh_token", b"refresh_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RefreshRequest: _TypeAlias = RefreshRequest  # noqa: Y015

@_typing.final
class RevokeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RevokeRequest: _TypeAlias = RevokeRequest  # noqa: Y015

@_typing.final
class Session(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LAST_USED_AT_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    IP_ADDRESS_FIELD_NUMBER: _builtins.int
    USER_AGENT_FIELD_NUMBER: _builtins.int
    AUTH_METHOD_FIELD_NUMBER: _builtins.int
    CURRENT_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    created_at: _builtins.str
    last_used_at: _builtins.str
    expires_at: _builtins.str
    ip_address: _builtins.str
    user_agent: _builtins.str
    auth_method: _builtins.str
    current: _builtins.bool
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        created_at: _builtins.str = ...,
        last_used_at: _builtins.str = ...,
        expires_at: _builtins.str = ...,
        ip_address: _builtins.str = ...,
        user_agent: _builtins.str = ...,
        auth_method: _builtins.str = ...,
        current: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_method", b"auth_method", "created_at", b"created_at", "current", b"current", "expires_at", b"expires_at", "ip_address", b"ip_address", "last_used_at", b"last_used_at", "session_id", b"session_id", "user_agent", b"user_agent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Session: _TypeAlias = Session  # noqa: Y015

@_typing.final
class SessionList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    SESSIONS_FIELD_NUMBER: _builtins.int
    mode: _builtins.str
    @_builtins.property
    def sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Session]: ...
    def __init__(
        self,
        *,
        mode: _builtins.str = ...,
        sessions: _abc.Iterable[Global___Session] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "sessions", b"sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionList: _TypeAlias = SessionList  # noqa: Y015
