# Generated by Django 6.1 on 2026-08-24 12:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oauth_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("admin", "Administrator"),
                            ("expired", "Expired"),
                            ("rotated", "Rotated"),
                            ("reuse", "Reuse detected"),
                            ("password_changed", "Password changed"),
                            ("security_event", "Security event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="oauth_session.oauthsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session access token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionRevocation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=255)),
                ("access_tokens_revoked", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oauth_session_revocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocations",
                        to="oauth_session.oauthsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="oauthsession",
            index=models.Index(
                fields=["user", "revoked_at"], name="oauth_sessi_user_id_3de1b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthsession",
            index=models.Index(fields=["expires_at"], name="oauth_sessi_expires_5c8552_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionaccesstoken",
            index=models.Index(
                fields=["user", "expires_at"], name="oauth_sessi_user_id_3d2e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionaccesstoken",
            index=models.Index(
                fields=["session", "revoked_at"], name="oauth_sessi_session_545025_idx"
            ),
        ),
    ]
