# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apps.support.grpc import support_pb2 as apps_dot_support_dot_grpc_dot_support__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apps/support/grpc/support_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SupportControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Assign = channel.unary_unary(
                '/config.support.SupportController/Assign',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.AssignRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.AssignResult.FromString,
                _registered_method=True)
        self.Canned = channel.unary_unary(
                '/config.support.SupportController/Canned',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.CannedRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.CannedList.FromString,
                _registered_method=True)
        self.Categories = channel.unary_unary(
                '/config.support.SupportController/Categories',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.CategoryList.FromString,
                _registered_method=True)
        self.Claim = channel.unary_unary(
                '/config.support.SupportController/Claim',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.ClaimRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.ClaimResult.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/config.support.SupportController/Count',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.CountRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.CountResult.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/config.support.SupportController/Delete',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.DeleteRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.DeletedMessage.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/config.support.SupportController/Edit',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.EditRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.EditedMessage.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/config.support.SupportController/Get',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.GetRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.Ticket.FromString,
                _registered_method=True)
        self.Invite = channel.unary_unary(
                '/config.support.SupportController/Invite',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.InviteRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.InvitedParticipant.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.support.SupportController/List',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.ListRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TicketList.FromString,
                _registered_method=True)
        self.Messages = channel.unary_unary(
                '/config.support.SupportController/Messages',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.MessagesRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.MessageList.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/config.support.SupportController/Open',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.OpenRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.OpenedTicket.FromString,
                _registered_method=True)
        self.Priority = channel.unary_unary(
                '/config.support.SupportController/Priority',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.PriorityRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.PriorityResult.FromString,
                _registered_method=True)
        self.Rate = channel.unary_unary(
                '/config.support.SupportController/Rate',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.RateRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.RateResult.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/config.support.SupportController/Read',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.ReadRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.ReadResult.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/config.support.SupportController/Send',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.SendRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.SentMessage.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/config.support.SupportController/Stats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.StatsResult.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/config.support.SupportController/Status',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.StatusRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.StatusResult.FromString,
                _registered_method=True)
        self.Tag = channel.unary_unary(
                '/config.support.SupportController/Tag',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TagRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TagResult.FromString,
                _registered_method=True)
        self.Tags = channel.unary_unary(
                '/config.support.SupportController/Tags',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TagList.FromString,
                _registered_method=True)
        self.Typing = channel.unary_unary(
                '/config.support.SupportController/Typing',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TypingRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TypingResult.FromString,
                _registered_method=True)
        self.Unread = channel.unary_unary(
                '/config.support.SupportController/Unread',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadResult.FromString,
                _registered_method=True)
        self.UnreadTicket = channel.unary_unary(
                '/config.support.SupportController/UnreadTicket',
                request_serializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketRequest.SerializeToString,
                response_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketResult.FromString,
                _registered_method=True)


class SupportControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Assign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Canned(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Categories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Claim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Messages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Priority(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Typing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnreadTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupportControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Assign': grpc.unary_unary_rpc_method_handler(
                    servicer.Assign,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.AssignRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.AssignResult.SerializeToString,
            ),
            'Canned': grpc.unary_unary_rpc_method_handler(
                    servicer.Canned,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.CannedRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.CannedList.SerializeToString,
            ),
            'Categories': grpc.unary_unary_rpc_method_handler(
                    servicer.Categories,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.CategoryList.SerializeToString,
            ),
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.ClaimRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.ClaimResult.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.CountRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.CountResult.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.DeleteRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.DeletedMessage.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.EditRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.EditedMessage.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.GetRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.Ticket.SerializeToString,
            ),
            'Invite': grpc.unary_unary_rpc_method_handler(
                    servicer.Invite,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.InviteRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.InvitedParticipant.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.ListRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TicketList.SerializeToString,
            ),
            'Messages': grpc.unary_unary_rpc_method_handler(
                    servicer.Messages,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.MessagesRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.MessageList.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.OpenRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.OpenedTicket.SerializeToString,
            ),
            'Priority': grpc.unary_unary_rpc_method_handler(
                    servicer.Priority,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.PriorityRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.PriorityResult.SerializeToString,
            ),
            'Rate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rate,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.RateRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.RateResult.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.ReadRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.ReadResult.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.SendRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.SentMessage.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.StatsResult.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.StatusRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.StatusResult.SerializeToString,
            ),
            'Tag': grpc.unary_unary_rpc_method_handler(
                    servicer.Tag,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TagRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TagResult.SerializeToString,
            ),
            'Tags': grpc.unary_unary_rpc_method_handler(
                    servicer.Tags,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TagList.SerializeToString,
            ),
            'Typing': grpc.unary_unary_rpc_method_handler(
                    servicer.Typing,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.TypingRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.TypingResult.SerializeToString,
            ),
            'Unread': grpc.unary_unary_rpc_method_handler(
                    servicer.Unread,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadResult.SerializeToString,
            ),
            'UnreadTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.UnreadTicket,
                    request_deserializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketRequest.FromString,
                    response_serializer=apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.support.SupportController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.support.SupportController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SupportController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Assign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Assign',
            apps_dot_support_dot_grpc_dot_support__pb2.AssignRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.AssignResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Canned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Canned',
            apps_dot_support_dot_grpc_dot_support__pb2.CannedRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.CannedList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Categories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Categories',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.CategoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Claim',
            apps_dot_support_dot_grpc_dot_support__pb2.ClaimRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.ClaimResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Count',
            apps_dot_support_dot_grpc_dot_support__pb2.CountRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.CountResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Delete',
            apps_dot_support_dot_grpc_dot_support__pb2.DeleteRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.DeletedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Edit',
            apps_dot_support_dot_grpc_dot_support__pb2.EditRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.EditedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Get',
            apps_dot_support_dot_grpc_dot_support__pb2.GetRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Invite',
            apps_dot_support_dot_grpc_dot_support__pb2.InviteRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.InvitedParticipant.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/List',
            apps_dot_support_dot_grpc_dot_support__pb2.ListRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.TicketList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Messages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Messages',
            apps_dot_support_dot_grpc_dot_support__pb2.MessagesRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.MessageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Open',
            apps_dot_support_dot_grpc_dot_support__pb2.OpenRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.OpenedTicket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Priority(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Priority',
            apps_dot_support_dot_grpc_dot_support__pb2.PriorityRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.PriorityResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Rate',
            apps_dot_support_dot_grpc_dot_support__pb2.RateRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.RateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Read',
            apps_dot_support_dot_grpc_dot_support__pb2.ReadRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.ReadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Send',
            apps_dot_support_dot_grpc_dot_support__pb2.SendRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.SentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Stats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.StatsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Status',
            apps_dot_support_dot_grpc_dot_support__pb2.StatusRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.StatusResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Tag',
            apps_dot_support_dot_grpc_dot_support__pb2.TagRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.TagResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Tags',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.TagList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Typing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Typing',
            apps_dot_support_dot_grpc_dot_support__pb2.TypingRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.TypingResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/Unread',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.UnreadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnreadTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.support.SupportController/UnreadTicket',
            apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketRequest.SerializeToString,
            apps_dot_support_dot_grpc_dot_support__pb2.UnreadTicketResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
