"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ChallengeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOGIN_TICKET_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    login_ticket: _builtins.str
    method: _builtins.str
    def __init__(
        self,
        *,
        login_ticket: _builtins.str = ...,
        method: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["login_ticket", b"login_ticket", "method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChallengeRequest: _TypeAlias = ChallengeRequest  # noqa: Y015

@_typing.final
class Credentials(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_TYPE_FIELD_NUMBER: _builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: _builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: _builtins.int
    EXPIRES_IN_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    token_type: _builtins.str
    access_token: _builtins.str
    refresh_token: _builtins.str
    expires_in: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        token_type: _builtins.str = ...,
        access_token: _builtins.str = ...,
        refresh_token: _builtins.str = ...,
        expires_in: _builtins.int = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_token", b"access_token", "expires_in", b"expires_in", "refresh_token", b"refresh_token", "session_id", b"session_id", "token_type", b"token_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Credentials: _TypeAlias = Credentials  # noqa: Y015

@_typing.final
class EmailConfirmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TICKET_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    ticket: _builtins.str
    code: _builtins.str
    def __init__(
        self,
        *,
        ticket: _builtins.str = ...,
        code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "ticket", b"ticket"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EmailConfirmRequest: _TypeAlias = EmailConfirmRequest  # noqa: Y015

@_typing.final
class EnrolledFactor(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    CONFIRMED_FIELD_NUMBER: _builtins.int
    LAST_USED_AT_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    destination: _builtins.str
    confirmed: _builtins.bool
    last_used_at: _builtins.str
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        destination: _builtins.str = ...,
        confirmed: _builtins.bool = ...,
        last_used_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confirmed", b"confirmed", "destination", b"destination", "last_used_at", b"last_used_at", "method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnrolledFactor: _TypeAlias = EnrolledFactor  # noqa: Y015

@_typing.final
class FactorList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHODS_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    UNUSED_RECOVERY_CODES_FIELD_NUMBER: _builtins.int
    unused_recovery_codes: _builtins.int
    @_builtins.property
    def methods(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnrolledFactor]: ...
    @_builtins.property
    def available(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        methods: _abc.Iterable[Global___EnrolledFactor] | None = ...,
        available: _abc.Iterable[_builtins.str] | None = ...,
        unused_recovery_codes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available", b"available", "methods", b"methods", "unused_recovery_codes", b"unused_recovery_codes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FactorList: _TypeAlias = FactorList  # noqa: Y015

@_typing.final
class LoginResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUIRES_SECOND_FACTOR_FIELD_NUMBER: _builtins.int
    CREDENTIALS_FIELD_NUMBER: _builtins.int
    LOGIN_TICKET_FIELD_NUMBER: _builtins.int
    METHODS_FIELD_NUMBER: _builtins.int
    requires_second_factor: _builtins.bool
    login_ticket: _builtins.str
    @_builtins.property
    def credentials(self) -> Global___Credentials: ...
    @_builtins.property
    def methods(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        requires_second_factor: _builtins.bool = ...,
        credentials: Global___Credentials | None = ...,
        login_ticket: _builtins.str = ...,
        methods: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["credentials", b"credentials"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credentials", b"credentials", "login_ticket", b"login_ticket", "methods", b"methods", "requires_second_factor", b"requires_second_factor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoginResult: _TypeAlias = LoginResult  # noqa: Y015

@_typing.final
class Message(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DETAIL_FIELD_NUMBER: _builtins.int
    detail: _builtins.str
    def __init__(
        self,
        *,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Message: _TypeAlias = Message  # noqa: Y015

@_typing.final
class RecoveryCodes(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def codes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        codes: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["codes", b"codes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecoveryCodes: _TypeAlias = RecoveryCodes  # noqa: Y015

@_typing.final
class RemoveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveRequest: _TypeAlias = RemoveRequest  # noqa: Y015

@_typing.final
class SentCode(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TICKET_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    EXPIRES_IN_FIELD_NUMBER: _builtins.int
    ticket: _builtins.str
    channel: _builtins.str
    destination: _builtins.str
    expires_in: _builtins.int
    def __init__(
        self,
        *,
        ticket: _builtins.str = ...,
        channel: _builtins.str = ...,
        destination: _builtins.str = ...,
        expires_in: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "destination", b"destination", "expires_in", b"expires_in", "ticket", b"ticket"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SentCode: _TypeAlias = SentCode  # noqa: Y015

@_typing.final
class SmsConfirmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TICKET_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    ticket: _builtins.str
    code: _builtins.str
    def __init__(
        self,
        *,
        ticket: _builtins.str = ...,
        code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "ticket", b"ticket"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmsConfirmRequest: _TypeAlias = SmsConfirmRequest  # noqa: Y015

@_typing.final
class SmsEnrollRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PHONE_FIELD_NUMBER: _builtins.int
    phone: _builtins.str
    def __init__(
        self,
        *,
        phone: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["phone", b"phone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmsEnrollRequest: _TypeAlias = SmsEnrollRequest  # noqa: Y015

@_typing.final
class TotpConfirmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TotpConfirmRequest: _TypeAlias = TotpConfirmRequest  # noqa: Y015

@_typing.final
class TotpEnrolment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECRET_FIELD_NUMBER: _builtins.int
    OTPAUTH_URI_FIELD_NUMBER: _builtins.int
    secret: _builtins.str
    otpauth_uri: _builtins.str
    def __init__(
        self,
        *,
        secret: _builtins.str = ...,
        otpauth_uri: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["otpauth_uri", b"otpauth_uri", "secret", b"secret"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TotpEnrolment: _TypeAlias = TotpEnrolment  # noqa: Y015

@_typing.final
class VerifyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOGIN_TICKET_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    login_ticket: _builtins.str
    code: _builtins.str
    method: _builtins.str
    def __init__(
        self,
        *,
        login_ticket: _builtins.str = ...,
        code: _builtins.str = ...,
        method: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "login_ticket", b"login_ticket", "method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifyRequest: _TypeAlias = VerifyRequest  # noqa: Y015
