# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from infrastructure.auth.twofactor.grpc import auth_twofactor_pb2 as infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure/auth/twofactor/grpc/auth_twofactor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoFactorControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Challenge = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/Challenge',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.ChallengeRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
                _registered_method=True)
        self.EmailConfirm = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/EmailConfirm',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.EmailConfirmRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
                _registered_method=True)
        self.EmailEnroll = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/EmailEnroll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
                _registered_method=True)
        self.Methods = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/Methods',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.FactorList.FromString,
                _registered_method=True)
        self.RecoveryGenerate = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/RecoveryGenerate',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RecoveryCodes.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/Remove',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RemoveRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
                _registered_method=True)
        self.SmsConfirm = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/SmsConfirm',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsConfirmRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
                _registered_method=True)
        self.SmsEnroll = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/SmsEnroll',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsEnrollRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
                _registered_method=True)
        self.TotpConfirm = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/TotpConfirm',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpConfirmRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
                _registered_method=True)
        self.TotpEnroll = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/TotpEnroll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpEnrolment.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/config.auth_twofactor.TwoFactorController/Verify',
                request_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.VerifyRequest.SerializeToString,
                response_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.LoginResult.FromString,
                _registered_method=True)


class TwoFactorControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Challenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailConfirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailEnroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Methods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoveryGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmsConfirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmsEnroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotpConfirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotpEnroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoFactorControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Challenge': grpc.unary_unary_rpc_method_handler(
                    servicer.Challenge,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.ChallengeRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.SerializeToString,
            ),
            'EmailConfirm': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailConfirm,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.EmailConfirmRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.SerializeToString,
            ),
            'EmailEnroll': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailEnroll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.SerializeToString,
            ),
            'Methods': grpc.unary_unary_rpc_method_handler(
                    servicer.Methods,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.FactorList.SerializeToString,
            ),
            'RecoveryGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoveryGenerate,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RecoveryCodes.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RemoveRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.SerializeToString,
            ),
            'SmsConfirm': grpc.unary_unary_rpc_method_handler(
                    servicer.SmsConfirm,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsConfirmRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.SerializeToString,
            ),
            'SmsEnroll': grpc.unary_unary_rpc_method_handler(
                    servicer.SmsEnroll,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsEnrollRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.SerializeToString,
            ),
            'TotpConfirm': grpc.unary_unary_rpc_method_handler(
                    servicer.TotpConfirm,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpConfirmRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.SerializeToString,
            ),
            'TotpEnroll': grpc.unary_unary_rpc_method_handler(
                    servicer.TotpEnroll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpEnrolment.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.VerifyRequest.FromString,
                    response_serializer=infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.LoginResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.auth_twofactor.TwoFactorController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.auth_twofactor.TwoFactorController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoFactorController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Challenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/Challenge',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.ChallengeRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmailConfirm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/EmailConfirm',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.EmailConfirmRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmailEnroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/EmailEnroll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Methods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/Methods',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.FactorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoveryGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/RecoveryGenerate',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RecoveryCodes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/Remove',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.RemoveRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmsConfirm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/SmsConfirm',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsConfirmRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmsEnroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/SmsEnroll',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SmsEnrollRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.SentCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotpConfirm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/TotpConfirm',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpConfirmRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotpEnroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/TotpEnroll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.TotpEnrolment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.auth_twofactor.TwoFactorController/Verify',
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.VerifyRequest.SerializeToString,
            infrastructure_dot_auth_dot_twofactor_dot_grpc_dot_auth__twofactor__pb2.LoginResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
