"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ContentField(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    MULTIPLE_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    VALUE_JSON_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    type: _builtins.str
    multiple: _builtins.bool
    required: _builtins.bool
    value_json: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        type: _builtins.str = ...,
        multiple: _builtins.bool = ...,
        required: _builtins.bool = ...,
        value_json: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "multiple", b"multiple", "name", b"name", "required", b"required", "type", b"type", "value_json", b"value_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ContentField: _TypeAlias = ContentField  # noqa: Y015

@_typing.final
class MenuDetail(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___MenuItem]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        items: _abc.Iterable[Global___MenuItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "items", b"items", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MenuDetail: _TypeAlias = MenuDetail  # noqa: Y015

@_typing.final
class MenuItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    NEW_TAB_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    page: _builtins.str
    url: _builtins.str
    new_tab: _builtins.bool
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        page: _builtins.str = ...,
        url: _builtins.str = ...,
        new_tab: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "new_tab", b"new_tab", "page", b"page", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MenuItem: _TypeAlias = MenuItem  # noqa: Y015

@_typing.final
class MenuList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MENUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def menus(self) -> _containers.RepeatedCompositeFieldContainer[Global___MenuSummary]: ...
    def __init__(
        self,
        *,
        menus: _abc.Iterable[Global___MenuSummary] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["menus", b"menus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MenuList: _TypeAlias = MenuList  # noqa: Y015

@_typing.final
class MenuRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    language: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        language: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["language", b"language", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MenuRequest: _TypeAlias = MenuRequest  # noqa: Y015

@_typing.final
class MenuSummary(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MenuSummary: _TypeAlias = MenuSummary  # noqa: Y015

@_typing.final
class PageDetail(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    SECTIONS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    language: _builtins.str
    status: _builtins.str
    @_builtins.property
    def meta(self) -> Global___PageMeta: ...
    @_builtins.property
    def sections(self) -> _containers.RepeatedCompositeFieldContainer[Global___Section]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        language: _builtins.str = ...,
        status: _builtins.str = ...,
        meta: Global___PageMeta | None = ...,
        sections: _abc.Iterable[Global___Section] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "language", b"language", "meta", b"meta", "name", b"name", "sections", b"sections", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageDetail: _TypeAlias = PageDetail  # noqa: Y015

@_typing.final
class PageList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pages(self) -> _containers.RepeatedCompositeFieldContainer[Global___PageSummary]: ...
    def __init__(
        self,
        *,
        pages: _abc.Iterable[Global___PageSummary] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pages", b"pages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageList: _TypeAlias = PageList  # noqa: Y015

@_typing.final
class PageMeta(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    OG_IMAGE_FIELD_NUMBER: _builtins.int
    OG_TITLE_FIELD_NUMBER: _builtins.int
    OG_DESCRIPTION_FIELD_NUMBER: _builtins.int
    OG_URL_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    description: _builtins.str
    og_image: _builtins.str
    og_title: _builtins.str
    og_description: _builtins.str
    og_url: _builtins.str
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        description: _builtins.str = ...,
        og_image: _builtins.str = ...,
        og_title: _builtins.str = ...,
        og_description: _builtins.str = ...,
        og_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "og_description", b"og_description", "og_image", b"og_image", "og_title", b"og_title", "og_url", b"og_url", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageMeta: _TypeAlias = PageMeta  # noqa: Y015

@_typing.final
class PageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    PREVIEW_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    language: _builtins.str
    preview: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        language: _builtins.str = ...,
        preview: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["language", b"language", "name", b"name", "preview", b"preview"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageRequest: _TypeAlias = PageRequest  # noqa: Y015

@_typing.final
class PageSummary(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    title: _builtins.str
    order: _builtins.int
    updated_at: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        title: _builtins.str = ...,
        order: _builtins.int = ...,
        updated_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "name", b"name", "order", b"order", "title", b"title", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageSummary: _TypeAlias = PageSummary  # noqa: Y015

@_typing.final
class PagesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: _builtins.int
    language: _builtins.str
    def __init__(
        self,
        *,
        language: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["language", b"language"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PagesRequest: _TypeAlias = PagesRequest  # noqa: Y015

@_typing.final
class Section(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SHARED_FIELD_NUMBER: _builtins.int
    FIELDS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    shared: _builtins.bool
    @_builtins.property
    def fields(self) -> _containers.RepeatedCompositeFieldContainer[Global___ContentField]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        shared: _builtins.bool = ...,
        fields: _abc.Iterable[Global___ContentField] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields", "id", b"id", "name", b"name", "shared", b"shared"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Section: _TypeAlias = Section  # noqa: Y015

@_typing.final
class SiteInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: _builtins.int
    LANGUAGES_FIELD_NUMBER: _builtins.int
    DEFAULT_LANGUAGE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TAGLINE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    LOGO_FIELD_NUMBER: _builtins.int
    FAVICON_FIELD_NUMBER: _builtins.int
    OG_IMAGE_FIELD_NUMBER: _builtins.int
    CONTACT_JSON_FIELD_NUMBER: _builtins.int
    SOCIAL_LINKS_JSON_FIELD_NUMBER: _builtins.int
    EXTRA_JSON_FIELD_NUMBER: _builtins.int
    OG_TITLE_FIELD_NUMBER: _builtins.int
    OG_DESCRIPTION_FIELD_NUMBER: _builtins.int
    OG_URL_FIELD_NUMBER: _builtins.int
    language: _builtins.str
    default_language: _builtins.str
    name: _builtins.str
    tagline: _builtins.str
    description: _builtins.str
    logo: _builtins.str
    favicon: _builtins.str
    og_image: _builtins.str
    contact_json: _builtins.str
    social_links_json: _builtins.str
    extra_json: _builtins.str
    og_title: _builtins.str
    og_description: _builtins.str
    og_url: _builtins.str
    @_builtins.property
    def languages(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        language: _builtins.str = ...,
        languages: _abc.Iterable[_builtins.str] | None = ...,
        default_language: _builtins.str = ...,
        name: _builtins.str = ...,
        tagline: _builtins.str = ...,
        description: _builtins.str = ...,
        logo: _builtins.str = ...,
        favicon: _builtins.str = ...,
        og_image: _builtins.str = ...,
        contact_json: _builtins.str = ...,
        social_links_json: _builtins.str = ...,
        extra_json: _builtins.str = ...,
        og_title: _builtins.str = ...,
        og_description: _builtins.str = ...,
        og_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["contact_json", b"contact_json", "default_language", b"default_language", "description", b"description", "extra_json", b"extra_json", "favicon", b"favicon", "language", b"language", "languages", b"languages", "logo", b"logo", "name", b"name", "og_description", b"og_description", "og_image", b"og_image", "og_title", b"og_title", "og_url", b"og_url", "social_links_json", b"social_links_json", "tagline", b"tagline"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SiteInfo: _TypeAlias = SiteInfo  # noqa: Y015

@_typing.final
class SiteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: _builtins.int
    language: _builtins.str
    def __init__(
        self,
        *,
        language: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["language", b"language"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SiteRequest: _TypeAlias = SiteRequest  # noqa: Y015
