# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from infrastructure.oauth.microsoft.grpc import oauth_microsoft_pb2 as infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure/oauth/microsoft/grpc/oauth_microsoft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MicrosoftOAuthControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/config.oauth_microsoft.MicrosoftOAuthController/Complete',
                request_serializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.CompleteRequest.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Credentials.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/config.oauth_microsoft.MicrosoftOAuthController/Start',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Authorization.FromString,
                _registered_method=True)


class MicrosoftOAuthControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MicrosoftOAuthControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.CompleteRequest.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Credentials.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Authorization.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.oauth_microsoft.MicrosoftOAuthController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.oauth_microsoft.MicrosoftOAuthController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MicrosoftOAuthController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_microsoft.MicrosoftOAuthController/Complete',
            infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.CompleteRequest.SerializeToString,
            infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Credentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.oauth_microsoft.MicrosoftOAuthController/Start',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            infrastructure_dot_oauth_dot_microsoft_dot_grpc_dot_oauth__microsoft__pb2.Authorization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
