# Generated by Django 6.1 on 2026-09-02 07:05

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("global", "Everyone"), ("user", "One account")],
                        default="user",
                        help_text="Whether this reaches one account or everybody.",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Where a client should go when somebody opens this.",
                        max_length=500,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Anything the sending code wants the client to have. Sent verbatim.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account this is for. Empty -- and required to be -- for a broadcast.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="notificatio_recipie_a972ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["audience", "-created_at"], name="notificatio_audienc_98ff43_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("audience", "user"), ("recipient__isnull", False)),
                    models.Q(("audience", "global"), ("recipient__isnull", True)),
                    _connector="OR",
                ),
                name="notification_audience_matches_recipient",
                violation_error_message="A user notification needs a recipient; a global one must not have any.",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationreceipt",
            constraint=models.UniqueConstraint(
                fields=("notification", "user"), name="notification_read_once_per_account"
            ),
        ),
    ]
