# Generated by Django 6.1 on 2026-09-03 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Receipts become per-account *state*, not just "this was read".

    ``read_at`` was non-null with a default, so its existence was the read state.
    Dismissing needs a second fact about the same pair, and undoing a read needs
    ``read_at`` to be clearable -- so both timestamps are nullable now. Existing
    rows keep the ``read_at`` they had and gain a null ``dismissed_at``, which
    reads as "read, still in the tray": exactly what they meant before.
    """

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationreceipt",
            name="dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this account cleared it away. Empty means still in the tray.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationreceipt",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="When this account read it. Empty means unread.", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="notificatio_created_46ad24_idx"),
        ),
    ]
