# Generated by Django 6.1 on 2026-08-24 12:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=32)),
                ("state_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("nonce_hash", models.CharField(blank=True, editable=False, max_length=64)),
                ("code_verifier_encrypted", models.TextField(blank=True, editable=False)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("next_url", models.CharField(default="/", max_length=500)),
                ("requested_scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_social_login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "expires_at"], name="oauth_core__provide_f22363_idx"
                    )
                ],
            },
        ),
    ]
