"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from infrastructure.oauth.google.grpc import oauth_google_pb2 as _oauth_google_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GoogleOAuthControllerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GoogleOAuthControllerAsyncStub: ...
    Complete: _grpc.UnaryUnaryMultiCallable[_oauth_google_pb2.CompleteRequest, _oauth_google_pb2.Credentials]
    Start: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _oauth_google_pb2.Authorization]

@_typing.type_check_only
class GoogleOAuthControllerAsyncStub(GoogleOAuthControllerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Complete: _aio.UnaryUnaryMultiCallable[_oauth_google_pb2.CompleteRequest, _oauth_google_pb2.Credentials]  # type: ignore[assignment]
    Start: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _oauth_google_pb2.Authorization]  # type: ignore[assignment]

class GoogleOAuthControllerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Complete(
        self,
        request: _oauth_google_pb2.CompleteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_oauth_google_pb2.Credentials, _abc.Awaitable[_oauth_google_pb2.Credentials]]: ...

    @_abc_1.abstractmethod
    def Start(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_oauth_google_pb2.Authorization, _abc.Awaitable[_oauth_google_pb2.Authorization]]: ...

def add_GoogleOAuthControllerServicer_to_server(servicer: GoogleOAuthControllerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
