syntax = "proto3";

package config.auth_magic_link;

service MagicLinkController {
    rpc LoginStart(LoginStartRequest) returns (LinkSent) {}
    rpc Logout(LogoutRequest) returns (Message) {}
    rpc SignupStart(SignupStartRequest) returns (LinkSent) {}
    rpc Verify(VerifyRequest) returns (LoginResult) {}
}

message Credentials {
    string token_type = 1;
    string access_token = 2;
    string refresh_token = 3;
    int32 expires_in = 4;
    string session_id = 5;
}

message LinkSent {
    string detail = 1;
    string destination = 2;
    int32 expires_in = 3;
}

message LoginResult {
    bool requires_second_factor = 1;
    Credentials credentials = 2;
    string login_ticket = 3;
    repeated string methods = 4;
}

message LoginStartRequest {
    string email = 1;
}

message LogoutRequest {
    string token = 1;
}

message Message {
    string detail = 1;
}

message SignupStartRequest {
    string email = 1;
}

message VerifyRequest {
    string token = 1;
}

