# Generated by Django 6.1 on 2026-09-02 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_checkout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ("-is_default", "-updated_at"),
                "verbose_name": "Delivery address",
                "verbose_name_plural": "Delivery addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ("code",),
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryreservation",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Stock reservation",
                "verbose_name_plural": "Stock reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Order line",
                "verbose_name_plural": "Order lines",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Shipping method",
                "verbose_name_plural": "Shipping methods",
            },
        ),
    ]
