# Generated by Django 6.1 on 2026-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="direct_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The two account ids of a direct message, smallest first. What makes opening a private chat idempotent: the second attempt finds the first rather than creating a parallel thread the other person is not reading.",
                max_length=80,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="A channel's address, so it can be linked to and found by name rather than by id. Null for every other kind, because only a channel is discoverable -- and null rather than blank so that the unique index permits any number of them.",
                max_length=140,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("agent", "Agent"),
                    ("observer", "Observer"),
                    ("owner", "Owner"),
                    ("member", "Member"),
                ],
                default="client",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chat", "Live chat"),
                    ("ticket", "Support ticket"),
                    ("channel", "Open channel"),
                    ("group", "Private group"),
                    ("direct", "Direct message"),
                ],
                default="ticket",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Empty is allowed: a live chat often has no subject until it turns out to need one. For a channel or a group this is its name, and it is required.",
                max_length=200,
            ),
        ),
    ]
