# Generated by Django 6.1 on 2026-08-25 10:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("signup", "Signup"),
                            ("code_sent", "Code sent"),
                            ("login_succeeded", "Login succeeded"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                            ("second_factor_required", "Second factor required"),
                            ("second_factor_succeeded", "Second factor succeeded"),
                            ("second_factor_failed", "Second factor failed"),
                            ("second_factor_enrolled", "Second factor enrolled"),
                            ("second_factor_removed", "Second factor removed"),
                            ("password_reset_requested", "Password reset requested"),
                            ("password_changed", "Password changed"),
                            ("throttled", "Throttled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=32)),
                ("identifier_hash", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="auth_core_a_event_t_db3a51_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="auth_core_a_user_id_11a6e0_idx"
                    ),
                    models.Index(
                        fields=["identifier_hash", "created_at"],
                        name="auth_core_a_identif_114439_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_phone_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_verified"], name="auth_core_p_user_id_dcf86b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("user",),
                        name="auth_unique_primary_phone",
                    )
                ],
            },
        ),
    ]
