# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apps.wallet.grpc import wallet_pb2 as apps_dot_wallet_dot_grpc_dot_wallet__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apps/wallet/grpc/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cancel = channel.unary_unary(
                '/config.wallet.WalletController/Cancel',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelResult.FromString,
                _registered_method=True)
        self.Checkpoints = channel.unary_unary(
                '/config.wallet.WalletController/Checkpoints',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointsRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointList.FromString,
                _registered_method=True)
        self.Convert = channel.unary_unary(
                '/config.wallet.WalletController/Convert',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeResult.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/config.wallet.WalletController/Deposit',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositResult.FromString,
                _registered_method=True)
        self.Entries = channel.unary_unary(
                '/config.wallet.WalletController/Entries',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntriesRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryPage.FromString,
                _registered_method=True)
        self.GetEntry = channel.unary_unary(
                '/config.wallet.WalletController/GetEntry',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryResult.FromString,
                _registered_method=True)
        self.GetWallet = channel.unary_unary(
                '/config.wallet.WalletController/GetWallet',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WalletResult.FromString,
                _registered_method=True)
        self.Methods = channel.unary_unary(
                '/config.wallet.WalletController/Methods',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodsRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodList.FromString,
                _registered_method=True)
        self.PriceMovement = channel.unary_unary(
                '/config.wallet.WalletController/PriceMovement',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteResult.FromString,
                _registered_method=True)
        self.Rates = channel.unary_unary(
                '/config.wallet.WalletController/Rates',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.RatesRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.RateList.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/config.wallet.WalletController/Transfer',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferResult.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/config.wallet.WalletController/Withdraw',
                request_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawResult.FromString,
                _registered_method=True)


class WalletControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Entries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Methods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceMovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelResult.SerializeToString,
            ),
            'Checkpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkpoints,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointsRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointList.SerializeToString,
            ),
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeResult.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositResult.SerializeToString,
            ),
            'Entries': grpc.unary_unary_rpc_method_handler(
                    servicer.Entries,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntriesRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryPage.SerializeToString,
            ),
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryResult.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WalletResult.SerializeToString,
            ),
            'Methods': grpc.unary_unary_rpc_method_handler(
                    servicer.Methods,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodsRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodList.SerializeToString,
            ),
            'PriceMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceMovement,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteResult.SerializeToString,
            ),
            'Rates': grpc.unary_unary_rpc_method_handler(
                    servicer.Rates,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.RatesRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.RateList.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferResult.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawRequest.FromString,
                    response_serializer=apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.wallet.WalletController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.wallet.WalletController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Cancel',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.CancelResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Checkpoints',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointsRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.CheckpointList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Convert',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.ExchangeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Deposit',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.DepositResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Entries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Entries',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntriesRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/GetEntry',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.EntryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/GetWallet',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.WalletResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Methods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Methods',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodsRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.MethodList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/PriceMovement',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.QuoteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Rates',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.RatesRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.RateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Transfer',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.TransferResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.wallet.WalletController/Withdraw',
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawRequest.SerializeToString,
            apps_dot_wallet_dot_grpc_dot_wallet__pb2.WithdrawResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
