"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from apps.wallet.grpc import wallet_pb2 as _wallet_pb2
from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WalletControllerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WalletControllerAsyncStub: ...
    Cancel: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.CancelRequest, _wallet_pb2.CancelResult]
    Checkpoints: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.CheckpointsRequest, _wallet_pb2.CheckpointList]
    Convert: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.ExchangeRequest, _wallet_pb2.ExchangeResult]
    Deposit: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.DepositRequest, _wallet_pb2.DepositResult]
    Entries: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.EntriesRequest, _wallet_pb2.EntryPage]
    GetEntry: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.EntryRequest, _wallet_pb2.EntryResult]
    GetWallet: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _wallet_pb2.WalletResult]
    Methods: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.MethodsRequest, _wallet_pb2.MethodList]
    PriceMovement: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.QuoteRequest, _wallet_pb2.QuoteResult]
    Rates: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.RatesRequest, _wallet_pb2.RateList]
    Transfer: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.TransferRequest, _wallet_pb2.TransferResult]
    Withdraw: _grpc.UnaryUnaryMultiCallable[_wallet_pb2.WithdrawRequest, _wallet_pb2.WithdrawResult]

@_typing.type_check_only
class WalletControllerAsyncStub(WalletControllerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Cancel: _aio.UnaryUnaryMultiCallable[_wallet_pb2.CancelRequest, _wallet_pb2.CancelResult]  # type: ignore[assignment]
    Checkpoints: _aio.UnaryUnaryMultiCallable[_wallet_pb2.CheckpointsRequest, _wallet_pb2.CheckpointList]  # type: ignore[assignment]
    Convert: _aio.UnaryUnaryMultiCallable[_wallet_pb2.ExchangeRequest, _wallet_pb2.ExchangeResult]  # type: ignore[assignment]
    Deposit: _aio.UnaryUnaryMultiCallable[_wallet_pb2.DepositRequest, _wallet_pb2.DepositResult]  # type: ignore[assignment]
    Entries: _aio.UnaryUnaryMultiCallable[_wallet_pb2.EntriesRequest, _wallet_pb2.EntryPage]  # type: ignore[assignment]
    GetEntry: _aio.UnaryUnaryMultiCallable[_wallet_pb2.EntryRequest, _wallet_pb2.EntryResult]  # type: ignore[assignment]
    GetWallet: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _wallet_pb2.WalletResult]  # type: ignore[assignment]
    Methods: _aio.UnaryUnaryMultiCallable[_wallet_pb2.MethodsRequest, _wallet_pb2.MethodList]  # type: ignore[assignment]
    PriceMovement: _aio.UnaryUnaryMultiCallable[_wallet_pb2.QuoteRequest, _wallet_pb2.QuoteResult]  # type: ignore[assignment]
    Rates: _aio.UnaryUnaryMultiCallable[_wallet_pb2.RatesRequest, _wallet_pb2.RateList]  # type: ignore[assignment]
    Transfer: _aio.UnaryUnaryMultiCallable[_wallet_pb2.TransferRequest, _wallet_pb2.TransferResult]  # type: ignore[assignment]
    Withdraw: _aio.UnaryUnaryMultiCallable[_wallet_pb2.WithdrawRequest, _wallet_pb2.WithdrawResult]  # type: ignore[assignment]

class WalletControllerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Cancel(
        self,
        request: _wallet_pb2.CancelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.CancelResult, _abc.Awaitable[_wallet_pb2.CancelResult]]: ...

    @_abc_1.abstractmethod
    def Checkpoints(
        self,
        request: _wallet_pb2.CheckpointsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.CheckpointList, _abc.Awaitable[_wallet_pb2.CheckpointList]]: ...

    @_abc_1.abstractmethod
    def Convert(
        self,
        request: _wallet_pb2.ExchangeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.ExchangeResult, _abc.Awaitable[_wallet_pb2.ExchangeResult]]: ...

    @_abc_1.abstractmethod
    def Deposit(
        self,
        request: _wallet_pb2.DepositRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.DepositResult, _abc.Awaitable[_wallet_pb2.DepositResult]]: ...

    @_abc_1.abstractmethod
    def Entries(
        self,
        request: _wallet_pb2.EntriesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.EntryPage, _abc.Awaitable[_wallet_pb2.EntryPage]]: ...

    @_abc_1.abstractmethod
    def GetEntry(
        self,
        request: _wallet_pb2.EntryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.EntryResult, _abc.Awaitable[_wallet_pb2.EntryResult]]: ...

    @_abc_1.abstractmethod
    def GetWallet(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.WalletResult, _abc.Awaitable[_wallet_pb2.WalletResult]]: ...

    @_abc_1.abstractmethod
    def Methods(
        self,
        request: _wallet_pb2.MethodsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.MethodList, _abc.Awaitable[_wallet_pb2.MethodList]]: ...

    @_abc_1.abstractmethod
    def PriceMovement(
        self,
        request: _wallet_pb2.QuoteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.QuoteResult, _abc.Awaitable[_wallet_pb2.QuoteResult]]: ...

    @_abc_1.abstractmethod
    def Rates(
        self,
        request: _wallet_pb2.RatesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.RateList, _abc.Awaitable[_wallet_pb2.RateList]]: ...

    @_abc_1.abstractmethod
    def Transfer(
        self,
        request: _wallet_pb2.TransferRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.TransferResult, _abc.Awaitable[_wallet_pb2.TransferResult]]: ...

    @_abc_1.abstractmethod
    def Withdraw(
        self,
        request: _wallet_pb2.WithdrawRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wallet_pb2.WithdrawResult, _abc.Awaitable[_wallet_pb2.WithdrawResult]]: ...

def add_WalletControllerServicer_to_server(servicer: WalletControllerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
