# Generated by Django 6.1 on 2026-08-24 12:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oauth_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlidingToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("admin", "Administrator"),
                            ("expired", "Expired"),
                            ("rotated", "Rotated"),
                            ("reuse", "Reuse detected"),
                            ("password_changed", "Password changed"),
                            ("security_event", "Security event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("issued_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("idle_timeout_seconds", models.PositiveIntegerField(default=900)),
                ("absolute_expires_at", models.DateTimeField()),
                ("previous_expires_at", models.DateTimeField(blank=True, null=True)),
                ("slide_count", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sliding token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SlidingTokenEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("slid", "Expiry extended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("old_expires_at", models.DateTimeField(blank=True, null=True)),
                ("new_expires_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="oauth_sliding.slidingtoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="slidingtoken",
            index=models.Index(
                fields=["user", "expires_at"], name="oauth_slidi_user_id_734fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slidingtoken",
            index=models.Index(
                fields=["absolute_expires_at", "revoked_at"], name="oauth_slidi_absolut_a685fe_idx"
            ),
        ),
    ]
