# Generated by Django 6.1.1 on 2026-09-12 16:08

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodCurrency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217 for money, or the ticker for an asset -- `USD`, `EUR`, `USDT`. Longer than three characters because crypto tickers are.",
                        max_length=12,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="The smallest movement accepted in this currency. Zero falls back to the method's.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="The largest. Zero falls back to the method's, and zero there means no ceiling.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "display_decimals",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How many decimals a client should show. Two for money, eight for a coin.",
                        validators=[django.core.validators.MaxValueValidator(8)],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "method currencies",
                "ordering": ["position", "currency"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "base",
                    models.CharField(help_text="The currency being converted from.", max_length=12),
                ),
                (
                    "quote",
                    models.CharField(help_text="The currency being converted to.", max_length=12),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=12,
                        help_text="One unit of base, in quote. Twelve decimals, because some pairs need them.",
                        max_digits=28,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="The spread kept on a conversion, always taken against the customer.",
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the number came from: a provider's name, or who typed it in.",
                        max_length=120,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this rate takes over from the one before it.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["base", "quote", "-effective_from"],
                        name="wallet_exch_base_a96bae_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base", "quote", "effective_from"),
                        name="wallet_rate_once_per_moment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gt", Decimal("0"))),
                        name="wallet_rate_positive",
                        violation_error_message="A rate of zero converts every amount to nothing.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MethodNetwork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="What the chain is called on an address label: `trc20`, `erc20`.",
                        max_length=40,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What a customer sees: `Tron (TRC20)`.", max_length=120
                    ),
                ),
                (
                    "confirmations",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many blocks the integration waits for before settling a deposit.",
                    ),
                ),
                (
                    "address_pattern",
                    models.CharField(
                        blank=True,
                        help_text="A regular expression an address on this chain matches, checked before a payout is recorded. Blank skips the check -- a wrong address here is money gone, so fill it in.",
                        max_length=255,
                    ),
                ),
                (
                    "network_fee",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="What the chain costs, in this asset, charged on withdrawals. Recorded against the entry as a `network` charge.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A floor for this chain alone. Zero falls back to the currency's.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "deposit_address",
                    models.CharField(
                        blank=True,
                        help_text="Where customers send this asset on this chain, if the deployment uses one address.",
                        max_length=255,
                    ),
                ),
                (
                    "explorer_url",
                    models.CharField(
                        blank=True,
                        help_text="A URL with `{tx}` in it, so a client can link a transaction hash.",
                        max_length=255,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="wallet.methodcurrency",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="What clients ask for this method by, such as `stripe-card` or `usdt-payout`. Stable: changing it breaks every client that stored it.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="What a customer sees in a list.", max_length=120),
                ),
                (
                    "rail",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("sepa", "SEPA"),
                            ("ach", "ACH"),
                            ("wire", "Wire"),
                            ("gateway", "Payment gateway"),
                            ("paypal", "PayPal"),
                            ("mobile_money", "Mobile money"),
                            ("crypto", "Crypto"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("voucher", "Voucher"),
                            ("internal", "Another wallet"),
                            ("system", "System"),
                        ],
                        help_text="The kind of thing this is. Decides settlement, reversibility and what the customer has to supply -- none of which this form can override.",
                        max_length=24,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A sentence for the customer choosing between methods.",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="What the customer has to actually do -- the counter to visit, the reference to quote. Shown after they pick this method.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="An icon name or URL, for whatever renders the list.",
                        max_length=120,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Off until somebody has filled in the currencies and the fees. A method published half configured quotes the wrong price.",
                    ),
                ),
                (
                    "supports_deposit",
                    models.BooleanField(default=True, help_text="Money can arrive this way."),
                ),
                (
                    "supports_withdrawal",
                    models.BooleanField(default=False, help_text="Money can leave this way."),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="On: a movement is a request an operator has to apply before it can settle. Off: the rail's own confirmation is enough.",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A fallback floor for currencies that do not set their own. Zero means no floor. Real limits belong on the currency.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A fallback ceiling. Zero means none.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Lower sorts first in the published list."
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Whatever the integration needs kept with the method: an account reference, a merchant id. Not secrets -- this is readable by anyone with admin access.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "position"], name="wallet_paym_is_enab_6af3c7_idx"
                    ),
                    models.Index(fields=["rail"], name="wallet_paym_rail_1b3696_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MethodFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("commission", "Commission"),
                            ("tax", "Tax"),
                            ("cost", "Processing cost"),
                            ("network", "Network fee"),
                            ("service", "Service fee"),
                        ],
                        default="commission",
                        max_length=16,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="What the customer sees on the record. Defaults to the kind's own name.",
                        max_length=120,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("credit", "Deposits"),
                            ("debit", "Withdrawals"),
                            ("both", "Both"),
                        ],
                        default="both",
                        help_text="A fee is rarely the same in both directions.",
                        max_length=8,
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Written as an operator writes it: 2.9 means 2.9%, not 290%.",
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "fixed",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A flat amount on top of the percentage, in the movement's currency.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[("gross", "The amount"), ("charges", "The charges before it")],
                        default="gross",
                        help_text="What the percentage is of. `The charges before it` is how VAT on a commission works.",
                        max_length=8,
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A floor on this charge. Zero means none.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="A cap on this charge. Zero means none.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "absorbed",
                    models.BooleanField(
                        default=False,
                        help_text="Recorded but not charged: a cost this deployment pays itself. The customer's amount is unaffected.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Order of application. It matters: a tax on the charges before it reads this.",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to charge this on every currency the method takes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="wallet.methodcurrency",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="wallet.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "kind"],
            },
        ),
        migrations.AddField(
            model_name="methodcurrency",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currencies",
                to="wallet.paymentmethod",
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217. Amounts are bare decimals, so this is the only record of what they mean.",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("frozen", "Frozen"), ("closed", "Closed")],
                        default="active",
                        help_text="Frozen refuses withdrawals and still accepts deposits.",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The account this wallet belongs to. Exactly one each.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="1 for the first checkpoint on this wallet, and no gaps after it."
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The settled balance as at this checkpoint: everything archived up to here.",
                        max_digits=18,
                    ),
                ),
                (
                    "credited",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Money in, across the entries archived here.",
                        max_digits=18,
                    ),
                ),
                (
                    "debited",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Money out, across the entries archived here.",
                        max_digits=18,
                    ),
                ),
                (
                    "entry_count",
                    models.PositiveIntegerField(
                        help_text="How many entries this checkpoint folded."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-sequence"],
            },
        ),
        migrations.CreateModel(
            name="WalletEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer_in", "Transfer in"),
                            ("transfer_out", "Transfer out"),
                            ("refund", "Refund"),
                            ("chargeback", "Chargeback"),
                            ("payment", "Payment"),
                            ("fee", "Fee"),
                            ("bonus", "Bonus"),
                            ("adjustment_credit", "Adjustment in"),
                            ("adjustment_debit", "Adjustment out"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "In"), ("debit", "Out")],
                        editable=False,
                        help_text="Derived from the kind, so the two cannot disagree.",
                        max_length=8,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("sepa", "SEPA"),
                            ("ach", "ACH"),
                            ("wire", "Wire"),
                            ("gateway", "Payment gateway"),
                            ("paypal", "PayPal"),
                            ("mobile_money", "Mobile money"),
                            ("crypto", "Crypto"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("voucher", "Voucher"),
                            ("internal", "Another wallet"),
                            ("system", "System"),
                        ],
                        help_text="The rail this movement travelled on.",
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What this moves the balance by, in the wallet's currency, after charges and after conversion. Always positive; direction says which way. This is the only field a balance is made of.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="The currency the customer named the movement in. Blank means the wallet's own -- the ordinary case, and no conversion happened.",
                        max_length=12,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="The figure the customer actually asked for, in `currency`, before any charge came off it. What they will recognise on a statement.",
                        max_digits=18,
                    ),
                ),
                (
                    "fee_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="What the charges came to, in `currency`. Frozen here rather than recomputed from the fee table, because the fee table changes and what somebody was charged in March does not.",
                        max_digits=18,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        help_text="The rate this converted at, spread included. Stored on the entry because `what did we convert at?` has to be answerable years later, when the rate row that priced it has long been superseded.",
                        max_digits=28,
                        null=True,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="Where a payout went: an address, an IBAN, a masked card. Empty for money coming in.",
                        max_length=255,
                    ),
                ),
                (
                    "approval",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("requested", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_required",
                        help_text="Whether a person still has to apply this. A requested movement cannot settle.",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(
                        blank=True,
                        help_text="Why it was applied, or why it was not.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        help_text="`done` is money, and so is `reversed` -- its counterpart is what undid it.",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="The caller's idempotency key. Unique per wallet, so a retried request returns the first entry instead of moving the money twice.",
                        max_length=120,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="What the rail calls this: a processor charge id, a transaction hash.",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Whatever the integration needs kept with the entry.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When it became `done`. Empty until it does.",
                        null=True,
                    ),
                ),
                (
                    "checkpoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="The checkpoint that has already counted this. Empty means it still counts on its own.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="wallet.walletcheckpoint",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        help_text="The other half of a pair: the far side of an internal transfer, or the entry this one reverses.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counterparts",
                        to="wallet.walletentry",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        blank=True,
                        help_text="For crypto: the chain it travelled on. Which chain is not a detail -- see MethodNetwork.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallet.methodnetwork",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="The configured method this went through. Empty for the movements no customer chose: a transfer between wallets here, a fee, an operator's correction. Protected rather than cascading -- a method that has moved money is history, and history does not get deleted to tidy a list.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallet.paymentmethod",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The operator who applied or refused it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wallet entries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WalletCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("commission", "Commission"),
                            ("tax", "Tax"),
                            ("cost", "Processing cost"),
                            ("network", "Network fee"),
                            ("service", "Service fee"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="What the customer sees on this line.", max_length=120
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="The rate applied, as it stood then. Zero for a flat charge.",
                        max_digits=7,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What this line came to, in the movement's currency.",
                        max_digits=18,
                    ),
                ),
                (
                    "absorbed",
                    models.BooleanField(
                        default=False,
                        help_text="This deployment paid it rather than the customer. Recorded so the reporting adds up; it changed nothing about what they received.",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, help_text="The order they were applied in."),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "fee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rule that produced this, while it still exists.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="wallet.methodfee",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="wallet.walletentry",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="methodnetwork",
            constraint=models.UniqueConstraint(
                fields=("asset", "code"), name="wallet_method_network_once"
            ),
        ),
        migrations.AddIndex(
            model_name="methodfee",
            index=models.Index(
                fields=["method", "is_enabled", "position"], name="wallet_meth_method__02a8ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="methodcurrency",
            constraint=models.UniqueConstraint(
                fields=("method", "currency"), name="wallet_method_currency_once"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["status"], name="wallet_wall_status_7f7e68_idx"),
        ),
        migrations.AddIndex(
            model_name="walletcheckpoint",
            index=models.Index(
                fields=["wallet", "-sequence"], name="wallet_wall_wallet__b9aa4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="walletcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("wallet", "sequence"), name="wallet_checkpoint_sequence_once"
            ),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(
                fields=["wallet", "-created_at"], name="wallet_wall_wallet__006c46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(fields=["wallet", "status"], name="wallet_wall_wallet__615dd7_idx"),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(
                fields=["wallet", "checkpoint", "created_at"], name="wallet_wall_wallet__bd2898_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(
                fields=["external_reference"], name="wallet_wall_externa_3a9d18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(
                fields=["approval", "created_at"], name="wallet_wall_approva_146ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletentry",
            index=models.Index(
                fields=["payment_method", "status"], name="wallet_wall_payment_cda66d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="walletentry",
            constraint=models.UniqueConstraint(
                fields=("wallet", "reference"), name="wallet_entry_reference_once_per_wallet"
            ),
        ),
        migrations.AddConstraint(
            model_name="walletentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0"))),
                name="wallet_entry_amount_positive",
                violation_error_message="An entry's amount is positive; direction says which way.",
            ),
        ),
        migrations.AddIndex(
            model_name="walletcharge",
            index=models.Index(fields=["entry", "position"], name="wallet_wall_entry_i_4cca37_idx"),
        ),
    ]
