# Generated by Django 6.1.1 on 2026-09-14 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceAdjustment",
            fields=[],
            options={
                "verbose_name": "balance adjustment",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wallet.walletentry",),
        ),
    ]
