# Generated by Django 6.1 on 2026-08-25 10:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code_hash", models.CharField(editable=False, max_length=64)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="auth_twofac_user_id_da065a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code_hash"), name="auth_unique_recovery_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecondFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator app"),
                            ("sms", "SMS code"),
                            ("email", "Email code"),
                            ("recovery", "Recovery codes"),
                        ],
                        max_length=16,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("secret_encrypted", models.TextField(blank=True, editable=False)),
                ("last_counter", models.BigIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_factors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "confirmed_at"], name="auth_twofac_user_id_808f0e_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "method"), name="auth_unique_second_factor"
                    )
                ],
            },
        ),
    ]
