# Generated by Django 6.1 on 2026-09-02 12:54

import uuid
from decimal import Decimal

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in URLs and filters.", max_length=120, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order in a brand list."),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The name the API is asked for, for example laptops.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="An icon name a storefront knows how to draw.",
                        max_length=60,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order among its siblings."),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "meta_keywords",
                    models.JSONField(blank=True, default=list, help_text='["laptops", "gaming"]'),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to shoppers in a spec table.",
                        max_length=150,
                        verbose_name="Label",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="The key a client reads, for example screen-size.", max_length=80
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes or no"),
                            ("choice", "One of a list"),
                            ("multi_choice", "Several of a list"),
                            ("color", "Colour"),
                            ("date", "Date"),
                            ("url", "Link"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text='Shown after the value: "in", "kg", "W".',
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='The allowed values, for a choice attribute: ["S", "M", "L"].',
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="A product without an answer is flagged as incomplete.",
                    ),
                ),
                (
                    "is_variant",
                    models.BooleanField(
                        default=False,
                        help_text="Answered per variant -- size, colour -- rather than per product.",
                        verbose_name="Distinguishes variants",
                    ),
                ),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=True,
                        help_text="Offered as a filter on the category's product list.",
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category attribute",
                "verbose_name_plural": "Category attributes",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The name the API is asked for.", max_length=250, unique=True
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="One line under the name.", max_length=250
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="A paragraph, for cards and search results."
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="The full description, for the page."),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="The shop's own code for this product.",
                        max_length=64,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, help_text="EAN, UPC or ISBN.", max_length=64),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Before any discount.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The higher price to show struck through. Not a discount -- those have dates.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What it cost the shop. Never published.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Percent. Quoted alongside the price; this app does not add it on.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="A draft is invisible to the API. An archived product stays readable by id.",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to appear as soon as it is active, or set a date to wait for.",
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Appears in the featured listing, wherever a storefront puts it.",
                    ),
                ),
                (
                    "has_variants",
                    models.BooleanField(
                        default=False,
                        help_text="This product is sold in variants. Stock and any price override live on them.",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off for something that cannot run out, like a download.",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="Ignored when this product has variants -- they carry their own.",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5, help_text="At or below this, the admin says so."
                    ),
                ),
                (
                    "allow_backorder",
                    models.BooleanField(
                        default=False, help_text="Let it be added to a cart with nothing in stock."
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("length_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("width_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("height_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("meta_keywords", models.JSONField(blank=True, default=list)),
                (
                    "rating_average",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), editable=False, max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0, editable=False)),
                ("like_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "sales_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Units sold. Maintained by whatever takes the orders."
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in a hand-sorted list."
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="shop.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Decides which attributes this product answers.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="products", to="shop.tag"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Shown to shoppers: Summer sale.", max_length=150),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percent off"), ("amount", "Amount off")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent off, or an amount off, depending on the kind above.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="A cap, for a percentage: 20% off, at most 50.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave empty to start immediately.", null=True
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to run until it is turned off.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Breaks a tie when two campaigns save a shopper the same amount. Higher wins.",
                    ),
                ),
                (
                    "applies_to_all",
                    models.BooleanField(
                        default=False,
                        help_text="Ignores the two lists below.",
                        verbose_name="Everything in the shop",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Includes every category underneath the ones chosen.",
                        related_name="discounts",
                        to="shop.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(blank=True, related_name="discounts", to="shop.product"),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ("-priority", "-starts_at"),
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection item",
                "verbose_name_plural": "Collection items",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="shop.CollectionItem",
                to="shop.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="shop.categoryattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product attribute",
                "verbose_name_plural": "Product attributes",
                "ordering": ("attribute__order", "attribute__name"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="What the picture shows, for a screen reader.",
                        max_length=250,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="The one shown on cards and in search results."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "ordering": ("-is_primary", "order"),
            },
        ),
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Shown in a picker. Built from the options if empty.",
                        max_length=200,
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True, verbose_name="SKU")),
                (
                    "options",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text='The variant attributes this one answers: {"colour": "Red"}.',
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides the product's price. Leave empty to charge the same.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("image", models.URLField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variants",
                "ordering": ("order", "sku"),
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart item",
                "verbose_name_plural": "Cart items",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1 to 5.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for a moderator"),
                            ("approved", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "moderator_note",
                    models.CharField(
                        blank=True,
                        help_text="Why this was rejected. Never shown to shoppers.",
                        max_length=300,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent", "order"], name="shop_catego_parent__8eff77_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_active"], name="shop_catego_is_acti_59c89f_idx"),
        ),
        migrations.AddIndex(
            model_name="categoryattribute",
            index=models.Index(fields=["category", "order"], name="shop_catego_categor_865a75_idx"),
        ),
        migrations.AddConstraint(
            model_name="categoryattribute",
            constraint=models.UniqueConstraint(
                fields=("category", "code"), name="unique_category_attribute_code"
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["is_active", "starts_at", "ends_at"], name="shop_discou_is_acti_a6563e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "product"),
                name="unique_collection_product",
                violation_error_message="That product is already in this collection.",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"),
                name="unique_product_attribute",
                violation_error_message="This product already answers that attribute.",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "order"], name="shop_produc_product_d61400_idx"),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="one_primary_image_per_product",
                violation_error_message="This product already has a main image.",
            ),
        ),
        migrations.AddIndex(
            model_name="productlike",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_produc_user_id_008405_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productlike",
            constraint=models.UniqueConstraint(
                fields=("product", "user"),
                name="one_like_per_account_per_product",
                violation_error_message="You have already liked this product.",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "order"], name="shop_produc_product_de8e37_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "created_at"], name="shop_cartit_cart_id_cdeede_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "variant"),
                name="unique_cart_line",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("cart", "product"),
                name="unique_cart_line_without_variant",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "status", "-created_at"], name="shop_review_product_064eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_review_user_id_6a0a0d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "user"),
                name="one_review_per_account_per_product",
                violation_error_message="You have already reviewed this product.",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "published_at"], name="shop_produc_status_af1966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="shop_produc_categor_c9aecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand", "status"], name="shop_produc_brand_i_94257d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-sales_count"], name="shop_produc_sales_c_a58fd0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-rating_average", "-rating_count"], name="shop_produc_rating__0066da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="shop_produc_price_3b79b5_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", Decimal("0"))),
                name="product_price_not_negative",
                violation_error_message="A price cannot be negative.",
            ),
        ),
    ]
