# Generated by Django 6.1 on 2026-09-02 13:56

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_checkout_admin_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(editable=False, max_length=24, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment is expected. Blank means on receipt.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Printed on the invoice.")),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ("-issued_at",),
            },
        ),
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="The seller's own code.",
                        max_length=64,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What this seller charges. Campaigns apply to it the same way.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("refurbished", "Refurbished"), ("used", "Used")],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Days before this seller dispatches it."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="A hidden offer stays in the admin and leaves the API.",
                        verbose_name="Shown",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller offer",
                "verbose_name_plural": "Seller offers",
                "ordering": ("price", "lead_time_days"),
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden rows stay in the admin and disappear from the API.",
                        verbose_name="Shown",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in URLs and filters.", max_length=150, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order in a seller list."),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "ordering": ("order", "name"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_line",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_line_without_variant",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_name",
            field=models.CharField(
                blank=True,
                help_text="Who sold it, copied down. Empty means the shop itself.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoice", to="shop.order"
            ),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="shop.product",
            ),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for a product sold in variants, and empty for one that is not.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="shop.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                help_text="Which seller's offer this line is from. Empty means the product's own.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.productoffer",
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                help_text="Whose shelf it came off. Empty means the product's own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="shop.productoffer",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.productoffer",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "variant", "offer"),
                name="unique_cart_line",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offer__isnull", True)),
                fields=("cart", "product", "variant"),
                name="unique_cart_line_without_offer",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("cart", "product", "offer"),
                name="unique_cart_line_without_variant",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offer__isnull", True), ("variant__isnull", True)),
                fields=("cart", "product"),
                name="unique_cart_line_plain",
                violation_error_message="That is already in this cart.",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The account that manages this seller, if one does.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_sellers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="shop.seller"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.seller",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Who sells it at the price and stock on this page. Leave empty for the shop itself. Other sellers are added as offers.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop.seller",
            ),
        ),
        migrations.AddIndex(
            model_name="productoffer",
            index=models.Index(
                fields=["product", "is_active"], name="shop_produc_product_f79fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoffer",
            index=models.Index(
                fields=["seller", "is_active"], name="shop_produc_seller__8d90da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productoffer",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "seller"),
                name="unique_offer_per_seller",
                violation_error_message="That seller already offers this.",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoffer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("product", "seller"),
                name="unique_offer_per_seller_without_variant",
                violation_error_message="That seller already offers this.",
            ),
        ),
    ]
