# Generated by Django 6.1 on 2026-09-03 11:11

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_sellers_offers_invoices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True, help_text="Who is carrying it: Royal Mail, DHL.", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(
                blank=True, help_text="Where the shopper can follow it.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="The one a checkout offers first. There is at most one."
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A flat amount off. Fill this in or the percentage, not both.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percent off the basket. Fill this in or the amount, not both.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="free_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delivery is free on a basket at least this big. Empty means never.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        help_text="What the order became.",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who moved it. Empty for a step a gateway or a job took.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order event",
                "verbose_name_plural": "Order events",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"], name="shop_ordere_order_i_5b127a_idx"
                    )
                ],
            },
        ),
    ]
