# Generated by Django 6.1.1 on 2026-09-14 10:44

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        help_text="What a client names this club in a URL. Stable: changing it breaks links.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.URLField(
                        blank=True,
                        help_text="The club's own badge, shown beside a member's level badge.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed to new members"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "join_policy",
                    models.CharField(
                        choices=[("open", "Anyone may join"), ("invite", "An operator adds them")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "club",
                "verbose_name_plural": "clubs",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("left", "Left"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="club.club",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-joined_at",),
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable name for this mission within its club.", max_length=80
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "event",
                    models.CharField(
                        help_text="The registered event key this mission listens for, e.g. shop.order.paid.",
                        max_length=120,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Which of those events count, as a plain object: {"min_value": 100, "equals": {"currency": "USD"}}. Empty means all of them.',
                    ),
                ),
                (
                    "xp",
                    models.PositiveIntegerField(
                        help_text="What completing it pays, in XP.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("once", "Once per member"),
                            ("every_time", "Every time it happens"),
                            ("daily", "Once a day"),
                            ("weekly", "Once a week"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many matching events complete it once. 'Buy three things' is 3.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "ordering": ("club", "title"),
            },
        ),
        migrations.CreateModel(
            name="MissionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, help_text="Matching events seen since the current run began."
                    ),
                ),
                (
                    "completions",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times this member has finished it."
                    ),
                ),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to="club.membership",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="club.mission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "mission progress",
                "ordering": ("mission__title",),
            },
        ),
        migrations.CreateModel(
            name="XpAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "xp",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(
                        help_text="Idempotency key, unique per member. A repeat pays nothing twice.",
                        max_length=200,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="club.membership",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="club.mission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClubLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="The rung's number, from 1 upwards with no gaps.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What this rung is called: Bronze, Gold.", max_length=120
                    ),
                ),
                (
                    "xp_required",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total lifetime XP that reaches this rung. The first rung is 0: everybody starts somewhere.",
                    ),
                ),
                ("logo", models.URLField(blank=True, help_text="The badge for this rung.")),
                (
                    "perks",
                    models.TextField(
                        blank=True, help_text="What the member gets here, in words a member reads."
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "level",
                "ordering": ("club", "position"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "position"), name="club_level_position_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("club", "xp_required"), name="club_level_threshold_unique"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["club", "status"], name="club_member_club_id_57a400_idx"),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(fields=["event", "is_enabled"], name="club_missio_event_c4928a_idx"),
        ),
        migrations.AddConstraint(
            model_name="mission",
            constraint=models.UniqueConstraint(
                fields=("club", "code"), name="club_mission_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="missionprogress",
            constraint=models.UniqueConstraint(
                fields=("membership", "mission"), name="club_progress_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="xpaward",
            index=models.Index(
                fields=["membership", "-created_at"], name="club_xpawar_members_b33de8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="xpaward",
            constraint=models.UniqueConstraint(
                fields=("membership", "reference"), name="club_award_reference_unique"
            ),
        ),
    ]
