# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apps.cms.grpc import cms_pb2 as apps_dot_cms_dot_grpc_dot_cms__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apps/cms/grpc/cms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Menu = channel.unary_unary(
                '/config.cms.ContentController/Menu',
                request_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuRequest.SerializeToString,
                response_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuDetail.FromString,
                _registered_method=True)
        self.Menus = channel.unary_unary(
                '/config.cms.ContentController/Menus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuList.FromString,
                _registered_method=True)
        self.Page = channel.unary_unary(
                '/config.cms.ContentController/Page',
                request_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageRequest.SerializeToString,
                response_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageDetail.FromString,
                _registered_method=True)
        self.Pages = channel.unary_unary(
                '/config.cms.ContentController/Pages',
                request_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PagesRequest.SerializeToString,
                response_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageList.FromString,
                _registered_method=True)
        self.Site = channel.unary_unary(
                '/config.cms.ContentController/Site',
                request_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.SiteRequest.SerializeToString,
                response_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.SiteInfo.FromString,
                _registered_method=True)


class ContentControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Menu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Menus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Page(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Site(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Menu': grpc.unary_unary_rpc_method_handler(
                    servicer.Menu,
                    request_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuRequest.FromString,
                    response_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuDetail.SerializeToString,
            ),
            'Menus': grpc.unary_unary_rpc_method_handler(
                    servicer.Menus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.MenuList.SerializeToString,
            ),
            'Page': grpc.unary_unary_rpc_method_handler(
                    servicer.Page,
                    request_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageRequest.FromString,
                    response_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageDetail.SerializeToString,
            ),
            'Pages': grpc.unary_unary_rpc_method_handler(
                    servicer.Pages,
                    request_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PagesRequest.FromString,
                    response_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.PageList.SerializeToString,
            ),
            'Site': grpc.unary_unary_rpc_method_handler(
                    servicer.Site,
                    request_deserializer=apps_dot_cms_dot_grpc_dot_cms__pb2.SiteRequest.FromString,
                    response_serializer=apps_dot_cms_dot_grpc_dot_cms__pb2.SiteInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.cms.ContentController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.cms.ContentController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContentController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Menu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.cms.ContentController/Menu',
            apps_dot_cms_dot_grpc_dot_cms__pb2.MenuRequest.SerializeToString,
            apps_dot_cms_dot_grpc_dot_cms__pb2.MenuDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Menus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.cms.ContentController/Menus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_cms_dot_grpc_dot_cms__pb2.MenuList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Page(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.cms.ContentController/Page',
            apps_dot_cms_dot_grpc_dot_cms__pb2.PageRequest.SerializeToString,
            apps_dot_cms_dot_grpc_dot_cms__pb2.PageDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.cms.ContentController/Pages',
            apps_dot_cms_dot_grpc_dot_cms__pb2.PagesRequest.SerializeToString,
            apps_dot_cms_dot_grpc_dot_cms__pb2.PageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Site(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.cms.ContentController/Site',
            apps_dot_cms_dot_grpc_dot_cms__pb2.SiteRequest.SerializeToString,
            apps_dot_cms_dot_grpc_dot_cms__pb2.SiteInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
