# Generated by Django 6.1 on 2026-08-24 12:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import infrastructure.oauth.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthScope",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("client_id", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "client_secret_hash",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("public", "Public"), ("confidential", "Confidential")],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "token_endpoint_auth_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("client_secret_basic", "Client secret basic"),
                            ("client_secret_post", "Client secret post"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("redirect_uris", models.JSONField(default=list)),
                (
                    "grant_types",
                    models.JSONField(default=infrastructure.oauth.core.models.default_grant_types),
                ),
                (
                    "response_types",
                    models.JSONField(
                        default=infrastructure.oauth.core.models.default_response_types
                    ),
                ),
                ("audiences", models.JSONField(default=list)),
                ("is_first_party", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scopes",
                    models.ManyToManyField(
                        blank=True, related_name="clients", to="oauth_core.oauthscope"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OAuthAuthorizationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("redirect_uri", models.TextField()),
                ("scopes", models.JSONField(default=list)),
                ("audience", models.CharField(blank=True, max_length=255)),
                ("code_challenge", models.CharField(max_length=128)),
                (
                    "code_challenge_method",
                    models.CharField(choices=[("S256", "SHA-256")], default="S256", max_length=10),
                ),
                ("nonce", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="oauth_core.oauthclient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client", "expires_at"], name="oauth_core__client__2f07f5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("client_created", "Client created"),
                            ("consent_granted", "Consent granted"),
                            ("consent_revoked", "Consent revoked"),
                            ("code_issued", "Authorization code issued"),
                            ("token_issued", "Token issued"),
                            ("token_refreshed", "Token refreshed"),
                            ("token_revoked", "Token revoked"),
                            ("token_reuse", "Token reuse detected"),
                            ("auth_failure", "Authentication failure"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token_fingerprint", models.CharField(blank=True, max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oauth_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="oauth_core.oauthclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="oauth_core__event_t_ddb299_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="oauth_core.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scopes",
                    models.ManyToManyField(related_name="consents", to="oauth_core.oauthscope"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "client"), name="oauth_unique_consent")
                ],
            },
        ),
    ]
