# Generated by Django 6.1 on 2026-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth_core", "0002_socialloginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialloginattempt",
            name="binding_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
