# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure/common/grpc/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'infrastructure/common/grpc/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'infrastructure/common/grpc/common.proto\x12\rconfig.common\x1a\x1bgoogle/protobuf/empty.proto\"\x8c\x01\n\x06Health\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08is_ready\x18\x02 \x01(\x08\x12\x31\n\x06\x63hecks\x18\x03 \x03(\x0b\x32!.config.common.Health.ChecksEntry\x1a-\n\x0b\x43hecksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8d\x01\n\x10HealthController\x12;\n\x08Liveness\x12\x16.google.protobuf.Empty\x1a\x15.config.common.Health\"\x00\x12<\n\tReadiness\x12\x16.google.protobuf.Empty\x1a\x15.config.common.Health\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure.common.grpc.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTH_CHECKSENTRY']._loaded_options = None
  _globals['_HEALTH_CHECKSENTRY']._serialized_options = b'8\001'
  _globals['_HEALTH']._serialized_start=88
  _globals['_HEALTH']._serialized_end=228
  _globals['_HEALTH_CHECKSENTRY']._serialized_start=183
  _globals['_HEALTH_CHECKSENTRY']._serialized_end=228
  _globals['_HEALTHCONTROLLER']._serialized_start=231
  _globals['_HEALTHCONTROLLER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
