"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Balance(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENCY_FIELD_NUMBER: _builtins.int
    SETTLED_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    INCOMING_FIELD_NUMBER: _builtins.int
    OUTGOING_FIELD_NUMBER: _builtins.int
    PROJECTED_FIELD_NUMBER: _builtins.int
    HAS_PENDING_FIELD_NUMBER: _builtins.int
    CHECKPOINT_SEQUENCE_FIELD_NUMBER: _builtins.int
    UNARCHIVED_ENTRIES_FIELD_NUMBER: _builtins.int
    currency: _builtins.str
    settled: _builtins.str
    available: _builtins.str
    incoming: _builtins.str
    outgoing: _builtins.str
    projected: _builtins.str
    has_pending: _builtins.bool
    checkpoint_sequence: _builtins.int
    unarchived_entries: _builtins.int
    def __init__(
        self,
        *,
        currency: _builtins.str = ...,
        settled: _builtins.str = ...,
        available: _builtins.str = ...,
        incoming: _builtins.str = ...,
        outgoing: _builtins.str = ...,
        projected: _builtins.str = ...,
        has_pending: _builtins.bool = ...,
        checkpoint_sequence: _builtins.int = ...,
        unarchived_entries: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available", b"available", "checkpoint_sequence", b"checkpoint_sequence", "currency", b"currency", "has_pending", b"has_pending", "incoming", b"incoming", "outgoing", b"outgoing", "projected", b"projected", "settled", b"settled", "unarchived_entries", b"unarchived_entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Balance: _TypeAlias = Balance  # noqa: Y015

@_typing.final
class CancelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    entry_id: _builtins.str
    reason: _builtins.str
    def __init__(
        self,
        *,
        entry_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_id", b"entry_id", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelRequest: _TypeAlias = CancelRequest  # noqa: Y015

@_typing.final
class CancelResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> Global___Entry: ...
    def __init__(
        self,
        *,
        entry: Global___Entry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelResult: _TypeAlias = CancelResult  # noqa: Y015

@_typing.final
class Charge(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KIND_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    PERCENT_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    ABSORBED_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    label: _builtins.str
    percent: _builtins.str
    amount: _builtins.str
    absorbed: _builtins.bool
    def __init__(
        self,
        *,
        kind: _builtins.str = ...,
        label: _builtins.str = ...,
        percent: _builtins.str = ...,
        amount: _builtins.str = ...,
        absorbed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["absorbed", b"absorbed", "amount", b"amount", "kind", b"kind", "label", b"label", "percent", b"percent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Charge: _TypeAlias = Charge  # noqa: Y015

@_typing.final
class Checkpoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    BALANCE_FIELD_NUMBER: _builtins.int
    CREDITED_FIELD_NUMBER: _builtins.int
    DEBITED_FIELD_NUMBER: _builtins.int
    ENTRY_COUNT_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    sequence: _builtins.int
    balance: _builtins.str
    credited: _builtins.str
    debited: _builtins.str
    entry_count: _builtins.int
    created_at: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        sequence: _builtins.int = ...,
        balance: _builtins.str = ...,
        credited: _builtins.str = ...,
        debited: _builtins.str = ...,
        entry_count: _builtins.int = ...,
        created_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balance", b"balance", "created_at", b"created_at", "credited", b"credited", "debited", b"debited", "entry_count", b"entry_count", "id", b"id", "sequence", b"sequence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Checkpoint: _TypeAlias = Checkpoint  # noqa: Y015

@_typing.final
class CheckpointList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHECKPOINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def checkpoints(self) -> _containers.RepeatedCompositeFieldContainer[Global___Checkpoint]: ...
    def __init__(
        self,
        *,
        checkpoints: _abc.Iterable[Global___Checkpoint] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["checkpoints", b"checkpoints"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckpointList: _TypeAlias = CheckpointList  # noqa: Y015

@_typing.final
class CheckpointsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckpointsRequest: _TypeAlias = CheckpointsRequest  # noqa: Y015

@_typing.final
class Currency(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENCY_FIELD_NUMBER: _builtins.int
    MIN_AMOUNT_FIELD_NUMBER: _builtins.int
    MAX_AMOUNT_FIELD_NUMBER: _builtins.int
    DECIMALS_FIELD_NUMBER: _builtins.int
    NETWORKS_FIELD_NUMBER: _builtins.int
    currency: _builtins.str
    min_amount: _builtins.str
    max_amount: _builtins.str
    decimals: _builtins.int
    @_builtins.property
    def networks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Network]: ...
    def __init__(
        self,
        *,
        currency: _builtins.str = ...,
        min_amount: _builtins.str = ...,
        max_amount: _builtins.str = ...,
        decimals: _builtins.int = ...,
        networks: _abc.Iterable[Global___Network] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currency", b"currency", "decimals", b"decimals", "max_amount", b"max_amount", "min_amount", b"min_amount", "networks", b"networks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Currency: _TypeAlias = Currency  # noqa: Y015

@_typing.final
class DepositRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    EXTERNAL_REFERENCE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    amount: _builtins.str
    method: _builtins.str
    reference: _builtins.str
    currency: _builtins.str
    network: _builtins.str
    external_reference: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        amount: _builtins.str = ...,
        method: _builtins.str = ...,
        reference: _builtins.str = ...,
        currency: _builtins.str = ...,
        network: _builtins.str = ...,
        external_reference: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "currency", b"currency", "description", b"description", "external_reference", b"external_reference", "method", b"method", "network", b"network", "reference", b"reference"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DepositRequest: _TypeAlias = DepositRequest  # noqa: Y015

@_typing.final
class DepositResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> Global___Entry: ...
    def __init__(
        self,
        *,
        entry: Global___Entry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DepositResult: _TypeAlias = DepositResult  # noqa: Y015

@_typing.final
class EntriesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KIND_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    status: _builtins.str
    method: _builtins.str
    direction: _builtins.str
    limit: _builtins.int
    offset: _builtins.int
    def __init__(
        self,
        *,
        kind: _builtins.str = ...,
        status: _builtins.str = ...,
        method: _builtins.str = ...,
        direction: _builtins.str = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direction", b"direction", "kind", b"kind", "limit", b"limit", "method", b"method", "offset", b"offset", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EntriesRequest: _TypeAlias = EntriesRequest  # noqa: Y015

@_typing.final
class Entry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    PAYMENT_METHOD_FIELD_NUMBER: _builtins.int
    PAYMENT_METHOD_NAME_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    NETWORK_NAME_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    SIGNED_AMOUNT_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    WALLET_CURRENCY_FIELD_NUMBER: _builtins.int
    GROSS_AMOUNT_FIELD_NUMBER: _builtins.int
    FEE_TOTAL_FIELD_NUMBER: _builtins.int
    NET_AMOUNT_FIELD_NUMBER: _builtins.int
    CHARGES_FIELD_NUMBER: _builtins.int
    CONVERTED_FIELD_NUMBER: _builtins.int
    EXCHANGE_RATE_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SETTLED_FIELD_NUMBER: _builtins.int
    APPROVAL_FIELD_NUMBER: _builtins.int
    AWAITING_APPROVAL_FIELD_NUMBER: _builtins.int
    REVIEWED_AT_FIELD_NUMBER: _builtins.int
    REVIEW_NOTE_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    EXTERNAL_REFERENCE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    COUNTERPARTY_ID_FIELD_NUMBER: _builtins.int
    ARCHIVED_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    SETTLED_AT_FIELD_NUMBER: _builtins.int
    COUNTS_TOWARDS_BALANCE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    kind: _builtins.str
    direction: _builtins.str
    method: _builtins.str
    payment_method: _builtins.str
    payment_method_name: _builtins.str
    network: _builtins.str
    network_name: _builtins.str
    amount: _builtins.str
    signed_amount: _builtins.str
    currency: _builtins.str
    wallet_currency: _builtins.str
    gross_amount: _builtins.str
    fee_total: _builtins.str
    net_amount: _builtins.str
    converted: _builtins.bool
    exchange_rate: _builtins.str
    destination: _builtins.str
    status: _builtins.str
    settled: _builtins.bool
    approval: _builtins.str
    awaiting_approval: _builtins.bool
    reviewed_at: _builtins.str
    review_note: _builtins.str
    reference: _builtins.str
    external_reference: _builtins.str
    description: _builtins.str
    metadata: _builtins.str
    counterparty_id: _builtins.str
    archived: _builtins.bool
    created_at: _builtins.str
    settled_at: _builtins.str
    counts_towards_balance: _builtins.bool
    @_builtins.property
    def charges(self) -> _containers.RepeatedCompositeFieldContainer[Global___Charge]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        kind: _builtins.str = ...,
        direction: _builtins.str = ...,
        method: _builtins.str = ...,
        payment_method: _builtins.str = ...,
        payment_method_name: _builtins.str = ...,
        network: _builtins.str = ...,
        network_name: _builtins.str = ...,
        amount: _builtins.str = ...,
        signed_amount: _builtins.str = ...,
        currency: _builtins.str = ...,
        wallet_currency: _builtins.str = ...,
        gross_amount: _builtins.str = ...,
        fee_total: _builtins.str = ...,
        net_amount: _builtins.str = ...,
        charges: _abc.Iterable[Global___Charge] | None = ...,
        converted: _builtins.bool = ...,
        exchange_rate: _builtins.str = ...,
        destination: _builtins.str = ...,
        status: _builtins.str = ...,
        settled: _builtins.bool = ...,
        approval: _builtins.str = ...,
        awaiting_approval: _builtins.bool = ...,
        reviewed_at: _builtins.str = ...,
        review_note: _builtins.str = ...,
        reference: _builtins.str = ...,
        external_reference: _builtins.str = ...,
        description: _builtins.str = ...,
        metadata: _builtins.str = ...,
        counterparty_id: _builtins.str = ...,
        archived: _builtins.bool = ...,
        created_at: _builtins.str = ...,
        settled_at: _builtins.str = ...,
        counts_towards_balance: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "approval", b"approval", "archived", b"archived", "awaiting_approval", b"awaiting_approval", "charges", b"charges", "converted", b"converted", "counterparty_id", b"counterparty_id", "counts_towards_balance", b"counts_towards_balance", "created_at", b"created_at", "currency", b"currency", "description", b"description", "destination", b"destination", "direction", b"direction", "exchange_rate", b"exchange_rate", "external_reference", b"external_reference", "fee_total", b"fee_total", "gross_amount", b"gross_amount", "id", b"id", "kind", b"kind", "metadata", b"metadata", "method", b"method", "net_amount", b"net_amount", "network", b"network", "network_name", b"network_name", "payment_method", b"payment_method", "payment_method_name", b"payment_method_name", "reference", b"reference", "review_note", b"review_note", "reviewed_at", b"reviewed_at", "settled", b"settled", "settled_at", b"settled_at", "signed_amount", b"signed_amount", "status", b"status", "wallet_currency", b"wallet_currency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Entry: _TypeAlias = Entry  # noqa: Y015

@_typing.final
class EntryPage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    TOTAL_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    total: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___Entry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___Entry] | None = ...,
        total: _builtins.int = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "limit", b"limit", "offset", b"offset", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EntryPage: _TypeAlias = EntryPage  # noqa: Y015

@_typing.final
class EntryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_ID_FIELD_NUMBER: _builtins.int
    entry_id: _builtins.str
    def __init__(
        self,
        *,
        entry_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_id", b"entry_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EntryRequest: _TypeAlias = EntryRequest  # noqa: Y015

@_typing.final
class EntryResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> Global___Entry: ...
    def __init__(
        self,
        *,
        entry: Global___Entry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EntryResult: _TypeAlias = EntryResult  # noqa: Y015

@_typing.final
class Exchange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    RATE_FIELD_NUMBER: _builtins.int
    MARGIN_PERCENT_FIELD_NUMBER: _builtins.int
    EFFECTIVE_RATE_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    CONVERTED_FIELD_NUMBER: _builtins.int
    INVERTED_FIELD_NUMBER: _builtins.int
    base: _builtins.str
    quote: _builtins.str
    rate: _builtins.str
    margin_percent: _builtins.str
    effective_rate: _builtins.str
    amount: _builtins.str
    converted: _builtins.str
    inverted: _builtins.bool
    def __init__(
        self,
        *,
        base: _builtins.str = ...,
        quote: _builtins.str = ...,
        rate: _builtins.str = ...,
        margin_percent: _builtins.str = ...,
        effective_rate: _builtins.str = ...,
        amount: _builtins.str = ...,
        converted: _builtins.str = ...,
        inverted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "base", b"base", "converted", b"converted", "effective_rate", b"effective_rate", "inverted", b"inverted", "margin_percent", b"margin_percent", "quote", b"quote", "rate", b"rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Exchange: _TypeAlias = Exchange  # noqa: Y015

@_typing.final
class ExchangeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: _builtins.int
    BASE_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    amount: _builtins.str
    base: _builtins.str
    quote: _builtins.str
    direction: _builtins.str
    def __init__(
        self,
        *,
        amount: _builtins.str = ...,
        base: _builtins.str = ...,
        quote: _builtins.str = ...,
        direction: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "base", b"base", "direction", b"direction", "quote", b"quote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExchangeRequest: _TypeAlias = ExchangeRequest  # noqa: Y015

@_typing.final
class ExchangeResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXCHANGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def exchange(self) -> Global___Exchange: ...
    def __init__(
        self,
        *,
        exchange: Global___Exchange | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exchange", b"exchange"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exchange", b"exchange"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExchangeResult: _TypeAlias = ExchangeResult  # noqa: Y015

@_typing.final
class Fee(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KIND_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    APPLIES_TO_FIELD_NUMBER: _builtins.int
    PERCENT_FIELD_NUMBER: _builtins.int
    FIXED_FIELD_NUMBER: _builtins.int
    BASIS_FIELD_NUMBER: _builtins.int
    MINIMUM_FIELD_NUMBER: _builtins.int
    MAXIMUM_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    label: _builtins.str
    applies_to: _builtins.str
    percent: _builtins.str
    fixed: _builtins.str
    basis: _builtins.str
    minimum: _builtins.str
    maximum: _builtins.str
    currency: _builtins.str
    def __init__(
        self,
        *,
        kind: _builtins.str = ...,
        label: _builtins.str = ...,
        applies_to: _builtins.str = ...,
        percent: _builtins.str = ...,
        fixed: _builtins.str = ...,
        basis: _builtins.str = ...,
        minimum: _builtins.str = ...,
        maximum: _builtins.str = ...,
        currency: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["applies_to", b"applies_to", "basis", b"basis", "currency", b"currency", "fixed", b"fixed", "kind", b"kind", "label", b"label", "maximum", b"maximum", "minimum", b"minimum", "percent", b"percent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fee: _TypeAlias = Fee  # noqa: Y015

@_typing.final
class Method(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    RAIL_FIELD_NUMBER: _builtins.int
    FAMILY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    INSTRUCTIONS_FIELD_NUMBER: _builtins.int
    ICON_FIELD_NUMBER: _builtins.int
    DIRECTIONS_FIELD_NUMBER: _builtins.int
    SETTLES_IMMEDIATELY_FIELD_NUMBER: _builtins.int
    REVERSIBLE_FIELD_NUMBER: _builtins.int
    REQUIRES_APPROVAL_FIELD_NUMBER: _builtins.int
    NEEDS_NETWORK_FIELD_NUMBER: _builtins.int
    NEEDS_DESTINATION_FIELD_NUMBER: _builtins.int
    CURRENCIES_FIELD_NUMBER: _builtins.int
    FEES_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    name: _builtins.str
    rail: _builtins.str
    family: _builtins.str
    description: _builtins.str
    instructions: _builtins.str
    icon: _builtins.str
    settles_immediately: _builtins.bool
    reversible: _builtins.bool
    requires_approval: _builtins.bool
    needs_network: _builtins.bool
    needs_destination: _builtins.bool
    @_builtins.property
    def directions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def currencies(self) -> _containers.RepeatedCompositeFieldContainer[Global___Currency]: ...
    @_builtins.property
    def fees(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fee]: ...
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        name: _builtins.str = ...,
        rail: _builtins.str = ...,
        family: _builtins.str = ...,
        description: _builtins.str = ...,
        instructions: _builtins.str = ...,
        icon: _builtins.str = ...,
        directions: _abc.Iterable[_builtins.str] | None = ...,
        settles_immediately: _builtins.bool = ...,
        reversible: _builtins.bool = ...,
        requires_approval: _builtins.bool = ...,
        needs_network: _builtins.bool = ...,
        needs_destination: _builtins.bool = ...,
        currencies: _abc.Iterable[Global___Currency] | None = ...,
        fees: _abc.Iterable[Global___Fee] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "currencies", b"currencies", "description", b"description", "directions", b"directions", "family", b"family", "fees", b"fees", "icon", b"icon", "instructions", b"instructions", "name", b"name", "needs_destination", b"needs_destination", "needs_network", b"needs_network", "rail", b"rail", "requires_approval", b"requires_approval", "reversible", b"reversible", "settles_immediately", b"settles_immediately"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Method: _TypeAlias = Method  # noqa: Y015

@_typing.final
class MethodList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHODS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def methods(self) -> _containers.RepeatedCompositeFieldContainer[Global___Method]: ...
    def __init__(
        self,
        *,
        methods: _abc.Iterable[Global___Method] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["methods", b"methods"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MethodList: _TypeAlias = MethodList  # noqa: Y015

@_typing.final
class MethodsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DIRECTION_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    direction: _builtins.str
    currency: _builtins.str
    def __init__(
        self,
        *,
        direction: _builtins.str = ...,
        currency: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currency", b"currency", "direction", b"direction"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MethodsRequest: _TypeAlias = MethodsRequest  # noqa: Y015

@_typing.final
class Network(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    CONFIRMATIONS_FIELD_NUMBER: _builtins.int
    NETWORK_FEE_FIELD_NUMBER: _builtins.int
    MIN_AMOUNT_FIELD_NUMBER: _builtins.int
    MAX_AMOUNT_FIELD_NUMBER: _builtins.int
    DEPOSIT_ADDRESS_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    name: _builtins.str
    confirmations: _builtins.int
    network_fee: _builtins.str
    min_amount: _builtins.str
    max_amount: _builtins.str
    deposit_address: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        name: _builtins.str = ...,
        confirmations: _builtins.int = ...,
        network_fee: _builtins.str = ...,
        min_amount: _builtins.str = ...,
        max_amount: _builtins.str = ...,
        deposit_address: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "confirmations", b"confirmations", "deposit_address", b"deposit_address", "max_amount", b"max_amount", "min_amount", b"min_amount", "name", b"name", "network_fee", b"network_fee"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Network: _TypeAlias = Network  # noqa: Y015

@_typing.final
class Quote(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    METHOD_NAME_FIELD_NUMBER: _builtins.int
    RAIL_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    WALLET_CURRENCY_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    GROSS_FIELD_NUMBER: _builtins.int
    CHARGES_FIELD_NUMBER: _builtins.int
    FEE_TOTAL_FIELD_NUMBER: _builtins.int
    ABSORBED_TOTAL_FIELD_NUMBER: _builtins.int
    NET_FIELD_NUMBER: _builtins.int
    WALLET_AMOUNT_FIELD_NUMBER: _builtins.int
    SETTLEMENT_AMOUNT_FIELD_NUMBER: _builtins.int
    CONVERTED_FIELD_NUMBER: _builtins.int
    EXCHANGE_FIELD_NUMBER: _builtins.int
    REQUIRES_APPROVAL_FIELD_NUMBER: _builtins.int
    SETTLES_IMMEDIATELY_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    method_name: _builtins.str
    rail: _builtins.str
    direction: _builtins.str
    currency: _builtins.str
    wallet_currency: _builtins.str
    network: _builtins.str
    gross: _builtins.str
    fee_total: _builtins.str
    absorbed_total: _builtins.str
    net: _builtins.str
    wallet_amount: _builtins.str
    settlement_amount: _builtins.str
    converted: _builtins.bool
    requires_approval: _builtins.bool
    settles_immediately: _builtins.bool
    @_builtins.property
    def charges(self) -> _containers.RepeatedCompositeFieldContainer[Global___Charge]: ...
    @_builtins.property
    def exchange(self) -> Global___Exchange: ...
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        method_name: _builtins.str = ...,
        rail: _builtins.str = ...,
        direction: _builtins.str = ...,
        currency: _builtins.str = ...,
        wallet_currency: _builtins.str = ...,
        network: _builtins.str = ...,
        gross: _builtins.str = ...,
        charges: _abc.Iterable[Global___Charge] | None = ...,
        fee_total: _builtins.str = ...,
        absorbed_total: _builtins.str = ...,
        net: _builtins.str = ...,
        wallet_amount: _builtins.str = ...,
        settlement_amount: _builtins.str = ...,
        converted: _builtins.bool = ...,
        exchange: Global___Exchange | None = ...,
        requires_approval: _builtins.bool = ...,
        settles_immediately: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exchange", b"exchange"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["absorbed_total", b"absorbed_total", "charges", b"charges", "converted", b"converted", "currency", b"currency", "direction", b"direction", "exchange", b"exchange", "fee_total", b"fee_total", "gross", b"gross", "method", b"method", "method_name", b"method_name", "net", b"net", "network", b"network", "rail", b"rail", "requires_approval", b"requires_approval", "settlement_amount", b"settlement_amount", "settles_immediately", b"settles_immediately", "wallet_amount", b"wallet_amount", "wallet_currency", b"wallet_currency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Quote: _TypeAlias = Quote  # noqa: Y015

@_typing.final
class QuoteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    direction: _builtins.str
    amount: _builtins.str
    currency: _builtins.str
    network: _builtins.str
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        direction: _builtins.str = ...,
        amount: _builtins.str = ...,
        currency: _builtins.str = ...,
        network: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "currency", b"currency", "direction", b"direction", "method", b"method", "network", b"network"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QuoteRequest: _TypeAlias = QuoteRequest  # noqa: Y015

@_typing.final
class QuoteResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QUOTE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def quote(self) -> Global___Quote: ...
    def __init__(
        self,
        *,
        quote: Global___Quote | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["quote", b"quote"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["quote", b"quote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QuoteResult: _TypeAlias = QuoteResult  # noqa: Y015

@_typing.final
class Rate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    RATE_FIELD_NUMBER: _builtins.int
    MARGIN_PERCENT_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    EFFECTIVE_FROM_FIELD_NUMBER: _builtins.int
    base: _builtins.str
    quote: _builtins.str
    rate: _builtins.str
    margin_percent: _builtins.str
    source: _builtins.str
    effective_from: _builtins.str
    def __init__(
        self,
        *,
        base: _builtins.str = ...,
        quote: _builtins.str = ...,
        rate: _builtins.str = ...,
        margin_percent: _builtins.str = ...,
        source: _builtins.str = ...,
        effective_from: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "effective_from", b"effective_from", "margin_percent", b"margin_percent", "quote", b"quote", "rate", b"rate", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Rate: _TypeAlias = Rate  # noqa: Y015

@_typing.final
class RateList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RATES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rates(self) -> _containers.RepeatedCompositeFieldContainer[Global___Rate]: ...
    def __init__(
        self,
        *,
        rates: _abc.Iterable[Global___Rate] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rates", b"rates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RateList: _TypeAlias = RateList  # noqa: Y015

@_typing.final
class RatesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    base: _builtins.str
    quote: _builtins.str
    def __init__(
        self,
        *,
        base: _builtins.str = ...,
        quote: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "quote", b"quote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RatesRequest: _TypeAlias = RatesRequest  # noqa: Y015

@_typing.final
class TransferRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TO_USER_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    to_user_id: _builtins.str
    amount: _builtins.str
    reference: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        to_user_id: _builtins.str = ...,
        amount: _builtins.str = ...,
        reference: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "description", b"description", "reference", b"reference", "to_user_id", b"to_user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TransferRequest: _TypeAlias = TransferRequest  # noqa: Y015

@_typing.final
class TransferResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> Global___Entry: ...
    def __init__(
        self,
        *,
        entry: Global___Entry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TransferResult: _TypeAlias = TransferResult  # noqa: Y015

@_typing.final
class Wallet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    BALANCE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    currency: _builtins.str
    status: _builtins.str
    created_at: _builtins.str
    @_builtins.property
    def balance(self) -> Global___Balance: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        currency: _builtins.str = ...,
        status: _builtins.str = ...,
        created_at: _builtins.str = ...,
        balance: Global___Balance | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["balance", b"balance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balance", b"balance", "created_at", b"created_at", "currency", b"currency", "id", b"id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Wallet: _TypeAlias = Wallet  # noqa: Y015

@_typing.final
class WalletResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WALLET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def wallet(self) -> Global___Wallet: ...
    def __init__(
        self,
        *,
        wallet: Global___Wallet | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wallet", b"wallet"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["wallet", b"wallet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WalletResult: _TypeAlias = WalletResult  # noqa: Y015

@_typing.final
class WithdrawRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    EXTERNAL_REFERENCE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    amount: _builtins.str
    method: _builtins.str
    reference: _builtins.str
    currency: _builtins.str
    network: _builtins.str
    destination: _builtins.str
    external_reference: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        amount: _builtins.str = ...,
        method: _builtins.str = ...,
        reference: _builtins.str = ...,
        currency: _builtins.str = ...,
        network: _builtins.str = ...,
        destination: _builtins.str = ...,
        external_reference: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "currency", b"currency", "description", b"description", "destination", b"destination", "external_reference", b"external_reference", "method", b"method", "network", b"network", "reference", b"reference"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WithdrawRequest: _TypeAlias = WithdrawRequest  # noqa: Y015

@_typing.final
class WithdrawResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> Global___Entry: ...
    def __init__(
        self,
        *,
        entry: Global___Entry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WithdrawResult: _TypeAlias = WithdrawResult  # noqa: Y015
